### ISSUE TITLE
ER Diagram for Data Model

### ISSUE THREAD

**Issue by derari** [hpi-swt2/workshop-portal#1]
- [x] model
- [ ] implement

**Comment by chrisma** [comment]
![workshop-portal](https://cloud.githubusercontent.com/assets/1652117/18094198/edac729c-6ed2-11e6-8f20-35f2b18ec200.png)

**Comment by chrisma** [comment]
The 'Applcation' model was renamed to 'ApplicationLetter' to avoid confusion with the Rails 'Application'
