### ISSUE TITLE
US_2.14: Detailed Profile Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#102]
**As**
organiser

**I want to**
see a detailed profile page of other users (especially pupils) instead of only id and "Abitur im Jahr"

**In order to**
get necessary information about them :smirk:  

**Dependencies:** None

**Estimate:** 5

**Acceptance Criteria:**
- [ ] all provided profile data is displayed
- [ ] page can only be accessed by admins and organizers
- [ ] edit and delete buttons are removed except for user itself
- [ ] edit page cannot be accessed manually via url (.../profiles/[id]/edit)
- [ ] remove id field
- [ ] every user gets empty profile on creation

**Comment by Square0ne** [comment]
organizer (admin) 
block other users "edit page cannot be accessed manually via url (.../profiles/ [id]/edit)"
