### ISSUE TITLE
US_1.1: Consistent german language 🍪

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#11]
**As** 
user 

**I want to** 
have consistent german language in the GUI 

**in order to** 
have a great user experience. 

**5 🍪**

This is an important issue for the already existing system. In the future we expect this to be considered throughout the new features. The responsibility is restricted to tabs that no other team actively modifies.

- [ ] There is no mix of languages for names of input fields, error messages and the like

**Comment by MasterCarl** [comment]
As @TimBasel pointed out, localizations should be implemented using i18n (as in pull request #64)

**Comment by bjrne** [comment]
Adressed in more detail in #145 - #151.
