### ISSUE TITLE
US_3.19: Applications Back Button

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#111]
**As**
user 

**I want to**
push the back button on the applications details page

**in order to**
go back to the previous page

# Tasks

# Acceptance criteria

- When a user comes from the overview page and presses the back button, than he / she goes back to the overview page.

- When a user comes from the applications page and presses the back button, than he / she goes back to the applications page.

- When a user accepts / rejects applicants multiple times, the back button leads back to the previous page and does not result in the same page

**Comment by Baschdl** [comment]
@tobiduer Do you refer to the back button of the browser or a button on our page?

**Comment by tobiduer** [comment]
@Baschdl: The back button on the page AND the back button in the browser. But the back button in the page has a higher priority.

**Comment by tobiasduerschmid** [comment]
Is not applicable any more because all back buttons will be removed
