### ISSUE TITLE
US_1.16 Link not in ID 🍪3

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#115]
**As** 
user

**I want to** 
be able to click the name/title on the index pages and not the ID of an item to go to the detail page

**in order to** 
have a better user experience
 
which pages?
Anfragen
Meine Bewerbungen
Benutzerverwaltung

** 🍪**
Acceptance Criteria
 - [ ] The ID is not visible anymore
 - [ ] I can click on the name or description and arrive and the detail page

**Comment by bjrne** [comment]
@Helene0 Shouldn't the description be removed in #47? I guess it'll just be the name then?

**Comment by bjrne** [comment]
not relevant anymore
