### ISSUE TITLE
US_1.15 Filter on the application page 🍪40

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#116]
**As** 
organizer and coach

**I want to** 
be able to filter the applying people by status (angenommen, abgelehnt, [Nachrücker], and other properties

**in order to** 
get a better overview

** 🍪** 

Acceptance Criteria
 - [ ] I can choose my filter by clicking on the property (ex name) 
 - [ ] If I click the property again it is sorted in the opposite order

**Comment by MasterCarl** [comment]
In terms used in the project, this refers to the application letters overview found in the page for an event, right?

**Comment by MasterCarl** [comment]
@Helene0 The item "I can choose my filter by clicking on the property (ex name)" refers to sorting, right?

**Comment by bjrne** [comment]
I think we agreed on showing a popup for the application status where you can select all categories you want to see and just sorting for everything else, but please await Helenes comment on that.
