### ISSUE TITLE
US_5.6: Group accepted users by color 💰 5

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#119]
**As**
organizer

**I want to**
group the participants of one event

**in order to**
split the participants in little work groups.

## Acceptance criteria:
- Opportunity for 10 colors (light blue, dark blue, red, yellow, orange, light green, dark green, violett, pink, grey) in a dropdown OR every color with a color picker
- Opportunity to change the color during the camp 
- As organizer I want to label a specific user with an color on the participants page
- As organizer I want to see the column "group" and there I can see rectangle colors for each participant
- As organizer I want to sort by group colors to generate name badges for example. (#33)

##
- [x] Add group to model
- [x] Show on participants page
- [x] Implement color selector
- [x] Make selector save selection to db
- [x] Add support for sorting by group and agreement letter state

**Comment by h0rnyc0rny** [comment]
How much colors?
