### ISSUE TITLE
US_2.1: Change my application

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#12]
**As** 
pupil

**I want to**
be able to process my application up to the deadline. After this, no change is possible.

**in order to**
change my application anytime

**dependency:** #18

**estimate:** 3

**acceptance criteria:**
- [x] edit form displays the saved data
- [x] changes are saved in the database
- [x] error-handling if mandatory fields are empty (like in #20 and #40)
- [x] changes after deadline are not possible

**Comment by j3sk1n** [comment]
Estimate: 3

**Comment by j3sk1n** [comment]
**dependency:** #18
