### ISSUE TITLE
Application Review

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#123]
**As**
applicant

**I want to**
see the important information for my application before I confirm it

**in order to**
double check the information

# Tasks

# Acceptance criteria

- After submitting the application, the applicant sees his / her personal profile information and below the current application

- The age is replaced by the birthday

**Comment by bjrne** [comment]
@tobiduer @hpi-swt2/scrum-master-2016 is this already contained in another user story?

**Comment by tobiduer** [comment]
@bjrne: I do not think so. Did you find one?

**Comment by bjrne** [comment]
@tobiduer still the case?

**Comment by tobiduer** [comment]
has been done in #257

**Comment by Baschdl** [comment]
@tobiduer @bjrne Please close issues not until PR is merged and approve by PO

**Comment by tobiduer** [comment]
@Baschdl: This issue is a duplicate ;)
