### ISSUE TITLE
US_3.20: Hide non-application-related information

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#125]
**As**
organizer / coach 

**I want to**
see only the for the application selection relevant information on the application details page

**in order to**
concentrate on these

# Tasks

# Acceptance criteria

- The address, the school (and other personal information, that is not related to the selection process) is hidden in the application details page

- A button for visiting the applicant's profile is displayed to organizers but not shown for coaches

**Comment by Baschdl** [comment]
@tobiduer "The address and [...] is hidden in the application details page" Something is missing

**Comment by tobiduer** [comment]
@Baschdl: I changed the ac. 
To avoid further questions: The brackets mean, that there is nothing more to hide on the current state of the develop. This is just a hint for the future and a motivation of the US.

**Comment by Baschdl** [comment]
@tobiduer Am I right that only the admin should see this fields on the application details page? Where did you see the school?

**Comment by tobiasduerschmid** [comment]
@Baschdl: Yes you are right. I did not see the school but do not want to see it in the future ;) 
Therefore please add a test for this in this US.
