### ISSUE TITLE
US_3.21: Calendar entry for the event

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#126]
**As**
applicant

**I want to**
get a calendar entry for the event when I am accepted

**in order to**
just add it to my own calendar

# Tasks
- [ ] Research mail attachments :cookie: **3**
- [ ] Research ICS (for multiple events) :cookie: **3**

# Acceptance criteria

- Acceptance mails have a calendar entry in the attachment with the duration of the event

**Comment by Baschdl** [comment]
@hpi-swt2/team-d-16 We could maybe us something like the [icalendar gem](https://github.com/icalendar/icalendar). But it doesn't seem well maintained.

**Comment by tobiasduerschmid** [comment]
Will be reviewed, when #473 is fixed. #StopTheLine

**Comment by cmfcmf** [comment]
This is now ready to be reviewed @tobiduer @hendraet.
