### ISSUE TITLE
Do not reload the application overview page on changes

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#128]
**As**
organizer

**I want to**
mark multiple applicants as accepted and rejected very fast

**in order to**
save time

# Tasks

# Acceptance criteria

- The application overview page is not reloaded when the state of an application changes

**Comment by Baschdl** [comment]
@drs-m Will implement this 😄

**Comment by Baschdl** [comment]
Should be **dead** easy [like this](https://coderwall.com/p/kqb3xq/rails-4-how-to-partials-ajax-dead-easy), you only have to insert a `:remote => true`. But it doesn't seem to work.
