### ISSUE TITLE
Push Apply button only once

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#129]
**As**
applicant

**I want to** 
be redirected to the register or create profile page

**in order to**
push the apply button on a camp only once.

# Tasks

# Acceptance criteria

- When user who is not logged in, pushes the apply button, he / she can log in or register

- When a logged in user without profile pushes the apply button, the user is redirected to the profiles page

- Re-directions are not done automatically, but a message is shown to the user and a button for the corresponding action(s) is shown

- The login / register / create profile pages get a next button in this cases that result in the application page

- The user has to push the apply button only once regardless whether he / she has a profile and was not logged in, has no profile and was not logged in or has no profile and was logged in.

**Comment by hendraet** [comment]
Part of issues #65 and #88

**Comment by hendraet** [comment]
Part of issues #65 and #88
