### ISSUE TITLE
US_2.2: Upload motivation letter

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#13]
**As** 
pupil

**I want to**
be able to enter the motivation letter in the application form in a large text area

**in order to**
not limited in size

**estimate:** 1

**acceptance criteria**
- text area displays 10 lines
- text area supports scrolling if more than 10 lines are written
- "Programmiersprachen" field is 5 lines long
- make sure db can handle that much text

**Comment by j3sk1n** [comment]
Estimate: 5

**Comment by hendraet** [comment]
Checkbox are displayed next to title
User and Workshop is set automatically

**Comment by hendraet** [comment]
Add the following text over the "Programmiersprachen" field:
„Mit welchen Programmiersprachen hast du bereits Erfahrungen
gesammelt? Wie gut beherrscht du sie deiner Meinung nach (Anfänger,
Fortgeschrittener, Experte)? Was kannst du in den Programmiersprachen
realisieren/hast du realisiert? Je ausführlicher du diese Beschreibst, desto besser
können wir schon in der Vorbereitung der Veranstaltung darauf eingehen.
Programmierkenntnisse sind keine Voraussetzung zur Teilnahme. Diese
Information wird zur Gruppeneinteilung benötigt.“
