### ISSUE TITLE
Custom Application Attributes for events

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#130]
**As**
organizer

**I want to**
Enter custom attributes for an application for an event (e.g, programming skills, school, organization, ...)

**in order to**
customize the application page for my specific event

# Tasks

# Acceptance criteria

- When creating an event, custom text fields can be added to an event.

- These fields are displayed to the applicant on the application page.

- These results are shown on the application details page to coaches and organizers. 

# PO Notes

- Refinements for optional / mandatory, shown in the application details page to coach / organizer are done in other US

**Comment by bjrne** [comment]
@hpi-swt2/product-owner-2016 Could we have some guidance on the importance of this user story?

**Comment by tobiduer** [comment]
@bjrne: It is something between medium priority and high priority.

**Comment by bjrne** [comment]
Duplicate of #189.
