### ISSUE TITLE
US_1.2 Meaningful error messages

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#14]
**As** 
user 

**I want to** 
have meaningful error messages 

**in order to** 
recognize which kind of input error I made, why something is not working the way its supposed to...

The responsibility is restricted to tabs that no other team actively modifies.

- [ ] I want to understand what went wrong and what I can do to fix that when reading an error message

**Comment by bjrne** [comment]
Adressed in more detail in #145 - #151.
