### ISSUE TITLE
US_1.18: selection of filter

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#141]
**As** 
organizer and coach

**I want to** 
be able selecte from the sorted people (by status (angenommen, abgelehnt, [Nachrücker], and other properties) and only see angenommen, abgelehnt, [Nachrücker] or a combination of those

**in order to** 
get a better overview

** 🍪** 

Acceptance Criteria

 - [ ] I have a checkbox to choose if i want to see all different states of the application or only specific ones

**Comment by bjrne** [comment]
duplicate of #116
