### ISSUE TITLE
Consistent German language and meaningful error messages Start Page 💰 1

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#143]
**As** 
user 

**I want to** 
have consistent german language on the start page and meaningful error messages

**in order to** 
have a great user experience. 

This is an important issue for the already existing system. In the future we expect this to be considered throughout the new features.

- [ ] There is no mix of languages for names of input fields, error messages and the like
- [ ] I get error messages that explain what went wrong and what i can do to fix it

**Comment by radscheit** [comment]
@julisa99 The start page is almost empty. We can discuss whether the word "beim" is eloquent in this context or not, but beside this I don't see any issues. Please specify this task.

**Comment by julisa99** [comment]
Ah I see, please ask @tom95 from Team Helene, when he will do it and if he would do this story too.
