### ISSUE TITLE
Consistent german language and meaningful error messages on "Profilinfo"-page 💰 1

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#146]
**As** 
user 

**I want to** 
have consistent german language on the Profilinfo-page and meaningful error messages

**in order to** 
have a great user experience. 

This is an important issue for the already existing system. In the future we expect this to be considered throughout the new features.

- [ ] There is no mix of languages for names of input fields, error messages and the like
- [ ] I get error messages that explain what went wrong and what i can do to fix it
- [ ] rename "Profilinfo" into "Einstellungen"
- [ ] remove name field from "Einstellungen"

**Comment by hendraet** [comment]
@radscheit Die Arbeit würde mein Team übernehmen, da es auf der entsprechenden Seite die Funktionalität ändert.

**Comment by radscheit** [comment]
Ist aber irgendwie nervig, dass ihr mir schon wieder ne US klaut. Also einverstanden bin ich damit nicht.

**Comment by hendraet** [comment]
@radscheit Sorry, habe deinen Kommentar erst jetzt gesehen. Nächstes mal teilt dir jmd. anders mit, wenn es Änderungen gibt. (Ich hatte das bloß gemacht, weil es in dem Moment einfach am Schnellsten ging)

Wir wollen dir übrigens nicht mutwillig US klauen, sondern einfach dafür sorgen, dass nichts doppelt gemacht wird. Wäre ja Mist, wenn sich jmd. unnötig Arbeit macht.

**Comment by radscheit** [comment]
@hendraet Das habe ich euch ja nicht unterstellt :) Es ist eben nur ungünstig, wenn das im Laufenden Sprint passiert. Denn es wäre tatsächlich schon das dritte Mal, dass ich eine Story abgeben muss, die ich schon bearbeitet habe, also dass geleistete Arbeit meinerseits für die Katz ist. Das kann ja mal passieren, ist aber nervig, wenn es sich - wie in meinem Fall - häuft. :)

**Comment by radscheit** [comment]
P.S: Diese Story hat schon einen fertigen PR.
