### ISSUE TITLE
Consistent German language and meaningful error messages on the Application page 💰 1

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#147]
**As** 
user 

**I want to** 
have consistent german language on the Application page (from a organizer/coach perspective) and meaningful error messages

**in order to** 
have a great user experience. 

This is an important issue for the already existing system. In the future we expect this to be considered throughout the new features.

- [ ] There is no mix of languages for names of input fields, error messages and the like
- [ ] I get error messages that explain what went wrong and what i can do to fix it

**Comment by radscheit** [comment]
@julisa99 Is Application Page = Start Page?

**Comment by julisa99** [comment]
@radscheit no the application page is the site, where you(as organizer/coach) can see the applications for an event

**Comment by radscheit** [comment]
@julisa99 Ah ok, this is misleading. we have the term `application` as well as the term `applications` in the system. The first one refers to the start page, the second to what you wrote :)

**Comment by radscheit** [comment]
@julisa99 As far as I see, there is nothing to do.
