### ISSUE TITLE
US_2.3: Hide private data

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#15]
**As** 
pupil

**I want to**
only organizers (and admin) can see my private data (profile data + application data)

**in order to**
protect my privacy

**dependency:** #23

**estimate:** 8

**acceptance criteria:**
- users and tutors can't access applications
- it's not possible to access those sites by using the url
- an error should be displayed if the site is accessed by url

**Comment by j3sk1n** [comment]
Estimate: 8

**Comment by j3sk1n** [comment]
**dependency:** #23
