### ISSUE TITLE
First And Last Name In Registration

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#178]
**As**
pupil

**I want to**
enter my first and last name in the registration form

**In order to**
don't have to enter it again in the profile

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [ ] two fields in registration: "Vorname", "Nachname"
- [ ] remove "Name" field in registration
- [ ] save first name, last name in database
- [ ] first name, last name should already appear in profile when opened for the first time
- [ ] first name last name is displayed as caption of the dropdown in the navbar

**Comment by bjrne** [comment]
@julisa99 could you add the reason to close an issue as a comment or tag before closing it if there are no links to other issues/PRs yet? (duplicate, adressed somewhere else, completely irrelevant, etc.)
