### ISSUE TITLE
Variable Application Form Fields

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#189]
**As**
organiser

**I want to**
have custom fields that I can add to the application that a user has to fill out when applying for an event

**In order to**
make the platform more versatile

**Acceptance Criteria:**
- [ ] Fields can only be changed until it the new event is saved or drafted for the first time and that is made clear to the user by having a short description next to the title "Felder können nur in diesem Schritt angepasst werden und sind danach fest gesetzt."
- [ ] Should look like this but with the title "Bewerbungsfelder anpassen"
![anpassbare_bewerbung - page 1](https://cloud.githubusercontent.com/assets/16731894/21159965/7a3307a0-c183-11e6-8dbb-d0c6dfb14727.png)

We left out the tickboxes in order to make the us doable

**Subtasks:**
Migrations & JSOn Serializer Factory 🗓 ?
Validations 🗓 ?
Layout & Javascript 🗓 ?

**Comment by MasterCarl** [comment]
See PR #323
