### ISSUE TITLE
US_4.3a: Email lists for mailing to a few participants 💰 3

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#193]
**As**
organizer 

**I want to**
generate an email-list with all participants **or some groups** / **single persons** during the camp

**in order to**
avoid coping the email addresses.

**Attention**
Ask Team Dürschmid for mail UI und backend

**Acceptance Criteria**
- The sender of the Email can be a single person (e.g. lisa.ihde@student.hpi.de) or a mailing list (e.g. mintcamp2016@hpi.de)
- The receiver is a group or a single person
- Please ensure, that this will not lead to access violation
- participants overview with button to generate an email-list with all participants **or some groups (only team blue, etc.)**  or a **single person**
- the organizer can select the persons with checkboxes and then click the button to send an e-mail, in the next step, as organizer, I should write the email

**Comment by tobiasduerschmid** [comment]
@Raandom: Where can we find the button for sending the emails after selecting the receivers?

**Comment by julisa99** [comment]
Der Haken für "alle auswählen" ist verpixelt? Lässt sich das verbessern?
<img width="598" alt="haken" src="https://cloud.githubusercontent.com/assets/8758907/22629636/f3489642-ebe9-11e6-8e70-e0055933abf3.PNG">

Bitte setze den Button zum Email versenden rechts neben "Namensschilder ausdrucken".

**Comment by Blaidd-Drwg** [comment]
Die Checkbox wird vom Browser bereitgstellt, und deiner hat anscheinend entschieden, dass Vektorgrafiken nur was für Nerds sind.
Man könnte a) selber eine Vektorgrafik für diese eine Checkbox liefern (und hoffen, dass es in allen Browsern ok aussieht), oder b) die Checkbox kleinermachen.

**Comment by tobiasduerschmid** [comment]
@Raandom @Blaidd-Drwg: Who is the real assignee for this US?

In my Browser (Firefox), the layout seem to be broken. 
![bild1](https://cloud.githubusercontent.com/assets/16103359/22637836/af0eb456-ec44-11e6-8c06-1b82c2a1cbf8.png)
The "alle auswählen" checkbox is huge and should be directly beside the text.

**Comment by Blaidd-Drwg** [comment]
@tobiduer: @Raandom is, but I've spent so much time reviewing it that by now I'm pretty familiar with it :smile:

**Comment by Raandom** [comment]
I'll have a look at that checkbox, I'll probably end up just making it small. Thanx for the review gentlemen and (women).

**Comment by julisa99** [comment]
It's okay, have you updated it?

**Comment by tobiasduerschmid** [comment]
@julisa99: Yes, and I am happy with the current state :) 
How are you?
