### ISSUE TITLE
Navigation bar dropdown highlights wrong items

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#194]
<img width="522" alt="bildschirmfoto 2016-12-14 um 11 56 19" src="https://cloud.githubusercontent.com/assets/7229585/21179486/9d6d359e-c1f4-11e6-9111-2b81ce4fcfcc.png">
As admin:
When I click on "Mein Profil anlegen", "Benutzerverwaltung" gets highlighted too.
@hpi-swt2/scrum-master-2016

**Comment by bjrne** [comment]
It's worth noting that this only happens as an admin.

**Comment by nilsthamm** [comment]
On branch dev it's now fixed
