### ISSUE TITLE
US_2.18: Profilinfo

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#195]
**As**
organiser

**I want to**
completly rework the "Profilinfo" and Registration page

**In order to**
do you even read this?

**Dependencies:**

**Estimate:** 8

**Acceptance Criteria:**
- [x] Remove name field from registration
- [x] redirect after registration to profile
- [ ] create profile automatically on sign up
- [x] use mail in navbar instead of name
- [x] rename "Profilinfo" into "Einstellungen"
- [x] remove name field from "Einstellungen"
- [x] mail should be displayed and changeable
- [x] everything German

**Comment by Square0ne** [comment]
Funktion für Namen/Mail der auf Namen checkt und dann Namen/Mail anzeigt
