### ISSUE TITLE
Setup Gems

### ISSUE THREAD

**Issue by derari** [hpi-swt2/workshop-portal#2]
- [x] check if we actually want these gems

Gems:
- devise
- devise_openid_authenticatable
- cancancan
- twitter-bootstrap-rails
- devise-bootstrap-views
- bootstrap-tooltip-rails
- has_scope
- rubocop
- newrelic_rpm
- airbrake
- delocalize
- american_date
- uglifier
- turbolinks
- jquery-rails
- therubyracer
- jquery-turbolinks
- jquery-ui-rails

------
Development 
- sqlite3
- web-console
- spring
- better_errors
- binding_of_caller
- pry
- pry-rails

------
Test
- codeclimate-test-reporter
- simplecov

------
Development + Test
- byebug
- rspec-rails
- capybara
- factory_girl_rails
- i18n-tasks

------
Prod
- pg
- rails_12factor

------
Gems we recommend as comments in Gemfile (for special cases)
- sass-rails
- jbuilder
- sdoc
- nokogiri
- tzinfo-data
- bootstrap-datepicker-rails
- select2-rails
- simple_form
- database_cleaner
- webmock
- letter_opener

**Comment by chrisma** [comment]
Setup Travis and codeclimate + Errbit on Heroku instance.

**Comment by chrisma** [comment]
Errbite lives at: https://swt2-errbit-2016.herokuapp.com

**Comment by chrisma** [comment]
@alexanderernst Could you please update this ticket with the used gems? Thanks :)

**Comment by alexanderernst** [comment]
done
