### ISSUE TITLE
US_2.4: Profile Information

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#20]
**As** 
pupil

**I want to**
enter all important data in my profile

**in order to**
declare food requirements, allergies, private data 

Important Data is:
- Vorname *
- Name *
- Geschlecht *
- Geburtsdatum *
- (E-Mail *)
- Schule *
- Straße *
- PLZ *
- Ort *
- Bundesland *
- Land *
- voraussichtliches Abitur im Jahr 
(* = mandatory fields)

**Estimate:** 5

**Acceptance Criteria**

- A user cannot submit a form without completing all the mandatory fields
- Mandatory fields are marked as mandatory
- An error will be displayed if the not all mandatory fields are completed
- The error highlights which fields aren't completed
- The entered data is stored in the (user-)database
- All fields are "normal" input fields
- Validation "voraussichtliches Abitur im Jahr" field is a dropdown with years from now up to +15 years

**Comment by j3sk1n** [comment]
Estimate: 5

**Comment by hendraet** [comment]
Delete CV- and Mail-Field
Save date in the form in which it is entered
