### ISSUE TITLE
US_1.6: Event drafts 🍪2

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#21]
**As** 
organizer 

**I want to** 
define draft events that are not published immediately 

**in order to** 
modify them together with my peers or colleagues. 

**5 🍪**

- [ ] I am able to click a save ("Speichern") button when I am done with my camp creation so that my camp is saved but not published
- [ ] When I am ready to publish my Draft i can click on a Publish ("Veröffentlichen") button and my Event becomes public. (on edit and creation page)

**Comment by MasterCarl** [comment]
The model for workshop contains a field "active" (Boolean). Is this supposed to indicate whether a workshop is a draft?

**Comment by chrisma** [comment]
This field is part of the starting application that was provided. Please feel free to delete/rename/modify any fields or classes as you see fit.

**Comment by MasterCarl** [comment]
See pull request https://github.com/hpi-swt2/workshop-portal/pull/79
