### ISSUE TITLE
US_1.23: Anfragen Details page

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#219]
**As** 
organizer
 
**I want to** 
be able to click on an request from the request page and get the detail view. On that page i also want to be able to change the status from open to accepted, by clicking an "Anfrage annehmen" button

**in order to** 
get a detailed overview

**🍪**

**Comment by Baschdl** [comment]
@Helene0 I don't think a coach should be able to do this

**Comment by MasterCarl** [comment]
This user story is not ready yet since there's no field like 'accepted' in the schema for requests.

**Comment by tom95** [comment]
All other stories did not depend on an accepted field, so I would say you could add that field as part of this story.

**Comment by bjrne** [comment]
@MasterCarl Shouldn't an admin or organizer be able to view stuff like dress etc as well? Also, the labels are partly truncated and the heading is still in plural. Sorry for the late comments, my fault to not test this locally before approving the PR :/
<img width="539" alt="bildschirmfoto 2017-01-18 um 16 20 22" src="https://cloud.githubusercontent.com/assets/7229585/22069890/4f0957c2-dd9a-11e6-8461-e9de28a65980.png">
