### ISSUE TITLE
US_3.2: Create bundle email list for acceptance add_sample_events/ rejection

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#22]
**As** 
organizer

**I want to**
Send acceptance / cancellation e-mails to the applicants in a bundle

**in order to**
do everything in a washing-up ;)

**estimation: 8**

## Acceptance criteria

- When an organizer visits the overview page and at least one application is not classified as accepted or rejected, the buttons for email sending should be disabled with the hint (mouse over) that not all applicants are classified as accepted or rejected.

- When an organizer visits the overview page and all applicants are classified but there is a negative number of free places, an error hint should be displayed on mouse over.

- When an organizer visits the overview page and all applicants are marked as either accepted or rejected the buttons for sending acceptance / rejection and there is a non-negative number of free places should be enabled.

- There is a mail-to link to open your email client

- When an organizer hits one of these buttons, the list of email addresses of the corresponding receivers should be displayed in a dialog with a copy to clipboard button. When the list is pasted into the address field of an email client, this should be a valid a complete list of all accepted / rejected applicants. 

- Coaches and applicants never see this button.

**Comment by tobiduer** [comment]
Similar to US_4.3 (Refs #35)

**Comment by tobiduer** [comment]
Additional details: The sender of the Email can be a single person (e.g. tobias.duerschmid@student.hpi.de) or a mailing list (e.g. mintcamp2016@hpi.de). Please ensure, that this will not lead to access violation and discuss your solution with the HPI admins and Lisa Ihdes team.

**Comment by tobiduer** [comment]
**Acceptance criteria**
When an organizer visits the overview website and at least one application is not classified as accepted or rejected, the buttons for email sending should be disabled with the hint (mouse over) that not all applicants are classified as accepted or rejected.
When an organizer visits the overview website and all applicants are marked as either accepted or rejected the buttons for sending acceptance / rejection should be enabled.
When an organizer hits one of these buttons, the list of email addresses of the corresponding receivers should be displayed in a dialog with a copy to clipboard button. When the list is pasted into the address field of an email client, this should be a valid an complete list of all accepted / rejected applicants.

**Comment by tobiduer** [comment]
Feedback: Coaches see the buttons for sending emails. This should not be the case according to the acceptance criteria.
