### ISSUE TITLE
US_2.42: Login-/Registration-Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#232]
**As**
pupil

**I want**
only one site for registration and login

**In order to**
make registration more convenient

**Dependencies:**

**Estimate:** 5

**Acceptance Criteria:**
- [ ] should look like this: 
![anmeldung_seite](https://cloud.githubusercontent.com/assets/16731894/21613832/36dccd9c-d1d7-11e6-95cf-4bfd24e0497f.png)
- [ ] remove "Registrieren" link
- [ ] still check inputs and display errors correctly 
- [ ] also adapt errors on the page so that they are displayed correctly

**Comment by radscheit** [comment]
#261

**Comment by bjrne** [comment]
Are you sure you have the correct issue number @radscheit? I don't quite understand what you want to say.
