### ISSUE TITLE
UI Create/Edit  Event

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#238]
**As**
organiser

**I want**
the description field to support markdown

**In order to**
style my description more conveniently

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [ ] the description field should support markdown
- [ ] should be text area (default: 20 lines)
- [ ] text below the field should state: "Dieser Editor unterstüzt [Markdown](https://daringfireball.net/projects/markdown/syntax)"
- [ ] should have placeholder text: (hint)
```	
## Subheadline
lorem ipsum für einen absatz

## Lernziele
* a
* b
* c

## Hinweise
* a
* b
* c
```

**Comment by bjrne** [comment]
You should decide on a list of supported elements. For example, I experienced problems with this link format in several libraries: 
`[Dokument][1]

some content
more content
[1]: https://somelink.abc/index.html`

Pictures might also be a problem.

**Comment by Baschdl** [comment]
Pictures: GitHub-flavored markdown supports embedding of external images
