### ISSUE TITLE
New Event Detail Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#240]
**As**
user

**I want**
a not crappy looking event page

**In order to**
find all necessary information quickly

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [ ] should look like this: 
![bewerbung_wf](https://cloud.githubusercontent.com/assets/16731894/21650235/980344fc-d2a4-11e6-910c-67f145a90a95.jpg)
- [ ] for now no displaying of a picture is needed
- [ ] "Bewerben" button at the bottom

**Comment by bjrne** [comment]
I removed the markdown criteria because we moved this to a separate user story, see #258. This user story (#240) is only about a visual redesign now.

**Comment by bjrne** [comment]
@tom95 @LeaGe Please test this again with a screen width of 1000-1200px. The layout, especially all fields apart from the description have weird line breaks that disappear when using a wider or smaller screen size
