### ISSUE TITLE
US_3.24: Transition from Selection to Execution

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#241]
**As**
organizer

**I want the**
event to change its state to execution when the emails are send

**in order to**
be able to cancel the email send process

# Tasks

# Acceptance criteria

- When the organizer pushes the send button in the email page (for sending the acceptance or rejection emails), then the event should change its state to execution

- There are no other transitions to execution

See Epic_3.3: Application States (Refs #233)

**Comment by tobiasduerschmid** [comment]
Will be reviewed, when #473 is fixed. #StopTheLine
