### ISSUE TITLE
US_3.26: Send emails for acceptance of alternatives

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#243]
**As**
organizer 

**I want to**
send acceptance emails to alternatives 

**in order to**
notify them for participation in the event

**estimation: 5**

# Dependencies: 

* Refs issue #242 (Application canceled state)
Implementation can start after merging Pull request #523

# Tasks

# Acceptance criteria
- When the event is in the execution state and alternative applicants have been selected for participation in the event, then organizers should see a button for sending email for acceptance for alternatives.

- When an organizer pushes the button, the email page should be opened with the email address of all alternatives that have been marked as participants but no one more. 
- This includes that the acceptance mails can be send after sending the rejection mails and vise versa
See Epic_3.3: Application States (Refs #233)

**Comment by tobiasduerschmid** [comment]
This includes that the acceptance mails can be send after sending the rejection mails and vise versa
