### ISSUE TITLE
US_2.44: Profile/User-Settings

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#245]
**As**
user

**I want**
only one page to edit my profile and change my password

**In order to**
to be able to edit things easier and have an awesome time

**Dependencies:**

**Estimate:** 8

**Acceptance Criteria:**
- [ ] should look like this:
![nutzer-details](https://cloud.githubusercontent.com/assets/16731894/21850408/ca3efe46-d80a-11e6-9115-9c2ad4731dd2.png)

- [x] "Einstellungen"-Page should be removed
- [x] password and profile should be edited and saved independently
- [x] "Account löschen" should delete Account
- [x] profile data fields should be filled out with according data
- [x] extra box for changing mail

**Comment by cmfcmf** [comment]
Sorry for closing thiss.
