### ISSUE TITLE
UI: Application Process

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#248]
**As**
user

**I want**
the application process to be more convenient

**In order to**
to have a better time 

**Dependencies:** #185

**Estimate:**

**Acceptance Criteria:**
- [ ] no "Bewerben" buttons should be displayed (on any page!) after the deadline is over
- [ ] if user accesses application via the url he shouldn't be able to press the "Bewerben"-Button and the following banner should be displayed:
![image](https://cloud.githubusercontent.com/assets/16731894/21770439/9893e27c-d683-11e6-9c29-6432a8782fde.png)

- [ ] if already applied to an event "Bewerben" buttons should be replace with "Bewerbung anzeigen" and link to the application checking page. (Refs #185)

**Comment by tobiasduerschmid** [comment]
Migrated to #244
