### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#261]
**As**
organiser

**I want**
the site to have a good looking color scheme

**In order to**
make the user feel comfortable on the site

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [x] create color scheme which applies to all fonts and colored ui elements
- [x] shouldn't hurt the eye or trigger epileptic seizures

**Comment by radscheit** [comment]
Already rolled out.
