### ISSUE TITLE
Anfragen-page: values of columns interchanged

### ISSUE THREAD

**Issue by Baschdl** [hpi-swt2/workshop-portal#274]
Values in the columns "Erstellt am" und "Aktionen" on the Anfragen-page are interchanged
<img width="1059" alt="anfragen" src="https://cloud.githubusercontent.com/assets/3034832/21803125/f0eaf424-d728-11e6-8b1b-294a96b10cb0.png">

**Comment by bjrne** [comment]
@MasterCarl Did you fix this in #265? :) If not, could you add this?

**Comment by MasterCarl** [comment]
Yes I did. I'll close this issue as soon as I merge #265.

**Comment by bjrne** [comment]
Since #265 is already merged, I'll close this now. Feel free to reopen this @MasterCarl if it was not appropriate.
