### ISSUE TITLE
US_4.5: Eating habits & allergies 💰 3

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#28]
**As**
organizer 

**I would like to**
see a list of allergies and eating habits of the participants in the event that I organize 

**in order to**
discuss this with the food provider. 

**Acceptance Criteria**
- As organizer I can see on the event page the participants of the event and their allergies/eating information.
- The organizer can:
  - sort by eating habits groups (vegan, vegetarian and none)
  - or show allergies at the top
  - show detail allergies information: While holding the mouse on the symbol, you can see more information.
  - option for printing/generate pdf
  - show vegan, vegetarian and allergies symbol all the time (none have no symbol, and the following symbols are from iconfinder with cc0-license)
![vegan](https://cloud.githubusercontent.com/assets/8758907/20611166/49ce1042-b2a5-11e6-8234-97174879c6d7.png)
![allergien](https://cloud.githubusercontent.com/assets/8758907/20611164/49cac1da-b2a5-11e6-8579-e72d74230827.png)
![cheese](https://cloud.githubusercontent.com/assets/8758907/20611167/49cf4e12-b2a5-11e6-9937-9c471224b8fb.png)

<img width="635" alt="eating_allergies" src="https://cloud.githubusercontent.com/assets/8758907/20611192/e1fe3702-b2a5-11e6-86c9-5628569dffe2.PNG">

See [UI wireframe for details](https://wireframe.cc/R3GJ9g)

**Comment by tobiduer** [comment]
Dependency: Event, Role Pupil, Role Organizer

**Comment by radscheit** [comment]
@julisa99 Please provide the symbols mentioned in the user story :)

**Comment by radscheit** [comment]
@julisa99 Are the dependencies missing here?

**Comment by radscheit** [comment]
@julisa99 @tobiduer Is this US still up to date?

**Comment by julisa99** [comment]
Ja, wie kommst du darauf, dass sich das geändert hat?

**Comment by bjrne** [comment]
@pinussilvestrus Is this a duplicate? Please state why you are closing issues that have no branch/PR history or duplicates linked.
