### ISSUE TITLE
Every text centered after error

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#284]
After this error:
![image](https://cloud.githubusercontent.com/assets/16731894/21812819/85429aa2-d754-11e6-9456-b0d0d32f9897.png)
if you go back via the back button in the browser every text is centered on every page and doesn't change (only after reload with Ctrl + F5):
![image](https://cloud.githubusercontent.com/assets/16731894/21812850/9d286fc0-d754-11e6-921f-d984c5f7042c.png)

**Comment by Helene0** [comment]
**As**
user

**I want to**
see the page in all its beauty, even after something went wrong

**In order to**
get the full amazing workshop and event experience
