### ISSUE TITLE
Use Role-Based-Authorization for coaches and organizer

### ISSUE THREAD

**Issue by Baschdl** [hpi-swt2/workshop-portal#287]
Assuming an organizer is also a coach, we could use [Role-Based-Authorization](https://github.com/CanCanCommunity/cancancan/wiki/Role-Based-Authorization) to define the abilities cleaner.

**Comment by cmfcmf** [comment]
Please note that we use cancancan, not cancan :)

Sebastian Bischoff <notifications@github.com> schrieb am Di., 10. Jan.
2017, 23:17:

**Comment by Baschdl** [comment]
Thanks, updated link

**Comment by cmfcmf** [comment]
> Thanks, updated link

We already use the techniques described in the wiki page you linked. 👍 for closing this issue.

**Comment by bjrne** [comment]
@cmfcmf Do we also use [Role-Inheritance](https://github.com/CanCanCommunity/cancancan/wiki/Role-Based-Authorization#role-inheritance)? Because a lot of tests could be more beautiful and readable then.

**Comment by Baschdl** [comment]
We discovered this this morning, we are already using role inheritance. I think not everyone knows that.

**Comment by cmfcmf** [comment]
For future reference:

- [Role hierachy](https://github.com/hpi-swt2/workshop-portal/blob/dev/app/models/user.rb#L32-L38)
- [Abilities](https://github.com/hpi-swt2/workshop-portal/blob/dev/app/models/ability.rb)
