### ISSUE TITLE
Print name badges display error in dialog

### ISSUE THREAD

**Issue by Baschdl** [hpi-swt2/workshop-portal#288]
After clicking "Print name badges" on the event page this display error occurs ("NameDrucken?")

![alledrucken](https://cloud.githubusercontent.com/assets/3034832/21828551/55b9e60e-d791-11e6-9c76-1aea57213137.png)

**Comment by Baschdl** [comment]
Occurs when no applicants are selected -> empty table

**Comment by julisa99** [comment]
Button ist nun ausgegraut, wenn kein Teilnehmer existiert, somit erscheint der Fehler nicht mehr.
