### ISSUE TITLE
US_2.4.11: Check if subject and body of mail is empty

### ISSUE THREAD

**Issue by Baschdl** [hpi-swt2/workshop-portal#290]
**As**
organizer

**I DON't want**
to be able to send mails without a subject or body

**In order to**
to be awesome and not confuse poor pupils who get an empty mail from me

**Dependencies:**

**Estimate:** 3

**Acceptance Criteria:**
- [ ] subject field for mails should be mandatory
- [ ] body field for mails should be mandatory
- [ ] both should be marked as mandatory
- [ ] errors should be displayed if not filled in correctly
- [ ] mails shouldn't get sent if an error occurs

**Comment by cmfcmf** [comment]
This has been done as part of #268.
