### ISSUE TITLE
US_2.47: Organizer should have less rights than admins

### ISSUE THREAD

**Issue by nstrelow** [hpi-swt2/workshop-portal#294]
As already mentioned in #87 

**As**
organizer

**I want to**
adjust the roles of other users, but not of admins

**In order to**
not downgrade admins or give users admin rights

**Dependencies:** #87 

**Acceptance Criteria:**
- [ ] organizers can't change the role of anyone to admin (only admins can to this)
- [ ] organizers can't change the role of admins

**Comment by hendraet** [comment]
So machen wir das hier nicht :smile:
