### ISSUE TITLE
Remove all "Zurück"-/"Abbrechen"-Buttons

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#302]
**As**
organiser

**I want**
no cancel or back buttons

**In order to**
because they often don't work or lead to wrong pages

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [ ] buttons on the following sites are removed:
 - Profil erstellen
 - Veranstaltungseite für Organiser
 - Veranstaltungseite für User
 - Veranstaltung bearbeiten
 - Event erstellen
 - Anfrage stellen
 - Einstellungen (nur Link)
 - Mein Profil
 - Profil bearbeiten

**Comment by bjrne** [comment]
See #272
