### ISSUE TITLE
Intuitive Request Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#303]
**As**
pupil

**I want**
a more intuitive request page

**In order to**
create requests easily

**Estimate:**

**Acceptance Criteria:**
- [x] I have a title: Neue Anfrage stellen
- [x] all info about the requested workshop (Thema des Workshops, Zeitrahmen, Teilnehmeranzahl, Kenntnisstand, Anmerkungen) is supposed to move to the top
- [x] all info about the contact person should be displayed at the bottom 
- [x] between those filed there should be a small heading saying: "Persönliche Daten"
- [x] after I sent the request I want to be returned to the home page with the "Anfrage wurde erfolgreich abgesendet" (STILL ENGLISH RN)

**Comment by Baschdl** [comment]
A pupil shouldn't request workshops

**Comment by bjrne** [comment]
@hendraet "is supposed to move to the pub"
*top? Or what is 'pub' supposed to mean in this context? :)

**Comment by hendraet** [comment]
@bjrne it should say "top". Helene mistakenly wrote pub and found it funny to leave it like this. (Changed it.)
@Baschdl I could change it to user but for consistency I wrote "pupil" because that's the role with the lowest rights. (We won't be able to keep pupils from requesting workshops, because there is currently no way to distinguish between pupils and teachers.)

**Comment by Baschdl** [comment]
@hendraet As far as I know a teacher shouldn't have to create an account to request a workshop. Or did we change this?

**Comment by hendraet** [comment]
@Baschdl Yeah sorry for being imprecise again. It's correct that you don't have to have an account for creating a request but that also means that you can't distinguish between teachers and other people, e.g. pupils
