### ISSUE TITLE
Archive Page For Past Events

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#304]
**As**
pupil

**I want**
an archive page for past events

**In order to**
be able to browse past events

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [ ] archive page should have the same design as the event overview page (except apply buttons)
- [ ] should be reachable via button on the overview page ("Vergangene Veranstaltungen")
- [ ] button on the left over first event (in the same "line" as the new button for organisers)
- [x] overview page should now be sorted like main page so that the next events are displayed at the top (already done in #316)

**Comment by tobiasduerschmid** [comment]
@tom95: Could you please add sample data for previous events to allow us to test this feature and demonstrate it every time?

**Comment by bjrne** [comment]
@tobiduer It's not that easy and would require a medium sized refactoring

**Comment by tobiasduerschmid** [comment]
@bjrne: Then please propose another way, how we can see that the implementation fits the acceptance criteria.

**Comment by tobiasduerschmid** [comment]
As discussed on Slack, the check that denies creating past events will be removed and the sampled data will be added.

**Comment by tobiasduerschmid** [comment]
@tom95: Could you please add a title / headline ("Veranstaltungs-Archiv") for the archive page?
