### ISSUE TITLE
US_2.4.8: List Views

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#309]
**As**
pupil

**I want**
uniform list views for displaying data

**In order to**
look at it

**Estimate:** 5

**Acceptance Criteria:**
- [ ] **the application check page will be redesigned independently**
- [ ] text shouldn't collapse if too long (on the left side)
- [ ] add linebreaks when text is too long (size of the container element)
- [ ] "key value pairs" should be displayed next to each other (on application check page)
- [ ] indentation should be the same for all values

**Comment by nilsthamm** [comment]
Changed following list views:
- detail profile (reachable as admin over the role management page)
- request detail (reachable by clicking the title of a request on /requests page) 

Couldn't find more list views that looked strange

**Comment by hendraet** [comment]
:clap:
