### ISSUE TITLE
E-Mail after "Anfrage"

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#312]
**As**
user

**I want**
get a notification E-Mail when i sent my request

**In order to**
be sure that someone is working on my request and they received it

**Acceptance Criteria:**
- [x] An E-Mail is sent and received by the person that made the request.

Hallo!
Ihre Anfrage ist bei uns eingegangen und wir melden uns schnellstmöglich bei Ihnen um weitere Details abzustimmen. 

Mit freundlichen Grüßen

- [ ] OPTIONAL: personalize the E-Mail by including the name and the wishes that the person entered. 🍪 **3**

Hallo *Name*!

Ihre Anfrage mit den Wünschen *Wünsche* ist bei uns eingegangen und wir melden uns schnellstmöglich bei Ihnen um weitere Details abzustimmen. 

Mit freundlichen Grüßen

**Comment by bjrne** [comment]
Pay attention to #268 where quite the refactoring is in progress.

**Comment by bjrne** [comment]
Apparently the refactoring is not important for us. @Baschdl told me the email helper will stay untouched. So this is ready to go.

**Comment by Baschdl** [comment]
To be sure I will directly ask my team ;) @TimBasel @Lando-L

**Comment by bjrne** [comment]
ping @Baschdl @TimBasel @Lando-L

**Comment by Baschdl** [comment]
pong. Is this problem fixed?

**Comment by tobiasduerschmid** [comment]
The current email body is still: "Hallo! Ihre Anfrage ist bei uns eingegangen und wir melden uns schnellstmöglich bei Ihnen, um weitere Details abzustimmen."
@bjrne: Therefore I move this US to in progress

**Comment by bjrne** [comment]
@tobiduer This is exactly what we were trying to do. As you can see, the personalization is another subtask in the issue and will be accomplished in another PR.

**Comment by julisa99** [comment]
@bjrne 
- Zeilenumbruch nach "Hallo" fehlt
-  und "Viele Grüße [Zeilenumbruch]
das HPI Workshop Team" fehlt

**Comment by bjrne** [comment]
@julisa99 die Grußformel am ende ist anders als im Issue angegeben, deshalb war das noch nicht so. Kümmere mich drum. Kannst du das Issue so anpassen, dass es genau den Text enthält, den ihr haben wollt?

**Comment by bjrne** [comment]
@hpi-schuelerklub/swt2 I think this is sufficient for now, please reopen it if you deem otherwise.
