### ISSUE TITLE
Workshop Choice Bar

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#319]
**As**
user

**I want to**
have a slidebar with example workshop pictures and Topics for inspiration

**In order to**
know what kind of ws i could ask for

**Acceptance Criteria:**

- [ ] I have a display of options, ideally with pictures and a Title (topic) 
- [ ] OPTIONAL this could be in form of a slidebar

**Comment by radscheit** [comment]
@hendraet Please have a look on the screener attached. Is the first orange panel fitting to your expectations?

![bildschirmfoto 2017-01-28 um 00 47 13](https://cloud.githubusercontent.com/assets/6578648/22397313/0c6b150e-e56f-11e6-9858-4401146174e0.png)

**Comment by hendraet** [comment]
@radscheit Sorry, but I don't see an attachement

**Comment by radscheit** [comment]
@hendraet This is already a PR #438. Please check it, since the acceptance criteria are letting room for interpretation.

**Comment by julisa99** [comment]
@hendraet ?

**Comment by hendraet** [comment]
@julisa99 @radscheit Told Matthias that he should merge it into dev so I can review it.

**Comment by radscheit** [comment]
@julisa99 @hendraet Sorry I was distracted by my birthday and my final presentation for Dschool that will take place today. I will push it this night. :)

**Comment by radscheit** [comment]
@julisa99 @hendraet I just noticed that i already pushed it days ago: https://github.com/hpi-swt2/workshop-portal/pull/438 :)

**Comment by julisa99** [comment]
@radscheit really? I don't see it
<img width="729" alt="anfrage" src="https://cloud.githubusercontent.com/assets/8758907/22648984/4b29e0a2-ec79-11e6-9304-195ae6c90ce2.PNG">

**Comment by radscheit** [comment]
@julisa99 Wo hast du es dir denn angeschaut?

**Comment by hendraet** [comment]
@radscheit Sorry, but I have to reopen this issue. The autoscrolling is a nice idea but is just annoying when you try to read the text. Please remove it.

**Comment by hendraet** [comment]
@radscheit an please exchange the text. Just copy them from here: https://hpi.de/open-campus/schuelerakademie/projekttage.html

**Comment by radscheit** [comment]
@hendraet As an alternative for dropping autoplay, i could offer stopAutoplay on mousehover?

**Comment by hendraet** [comment]
Passt
