### ISSUE TITLE
CVAF static details page

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#322]
(**C**ustom **V**ariable **A**pplication **F**ields)
show custom fields in static application details page

**Comment by MasterCarl** [comment]
See PR #323

**Comment by MasterCarl** [comment]
I assigned myself since this is highly related to #321

**Comment by Baschdl** [comment]
For what does CVAF stand?

**Comment by bjrne** [comment]
**C**ustom **V**ariable **A**pplication **F**ields. Sorry, it was a joke in our team since we have 3 user stories with very similar names.
