### ISSUE TITLE
Users are able to create multiple profiles

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swt2/workshop-portal#325]
Steps to reproduce:
- Create a profile at `/profiles/new`
- Create another profile at `/profiles/new`

@hpi-swt2/scrum-master-2016

**Comment by bjrne** [comment]
👍 Thanks for reporting. I think the @hpi-swt2/product-owner-2016 should give this a look and modify the priority accordingly.

**Comment by Helene0** [comment]
**As**
user

**I DONT want to**
be able to create a second profile and want to get an error if i try to create a profile when one already exists

**In order to**
not create a new profile by mistake and not be able to do it on purpose either

**Comment by cmfcmf** [comment]
> be able to create a second profile and want to get an error if i try to create a profile with an email adress that already exists

Note: Profile != User account. The profile doesn't contain an email address, I don't think it's currently possible to create multiple user accounts with the same email address :)
