### ISSUE TITLE
The word "vegetarian" is misspelt in the db schema and that bothers me

### ISSUE THREAD

**Issue by Blaidd-Drwg** [hpi-swt2/workshop-portal#337]
Currently spelt ["vegeterian"](https://github.com/hpi-swt2/workshop-portal/blob/288b6f97c6ea3047ee3b76b1872f41074f2b3812/db/schema.rb#L38).

**Comment by Baschdl** [comment]
Yes, not only in the db schema. [All occurrences](https://github.com/hpi-swt2/workshop-portal/search?utf8=✓&q=vegeterian)
