### ISSUE TITLE
"Angenommen/abgelehnt" auf request overview page

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#364]
**As** 
organizer 

**I want to** 
see on the overview page if a request is already accepted or declined 
**in order to** 
have better overview

AC 
- [ ] I have a column on the overview page  next to "Teilnehmerzahl" called "Status" and they can either be Angenommen oder Abgelehent

**Comment by LeaGe** [comment]
@hpi-swt2/product-owner-2016 was ist mit dem status "Noch nicht angenommen" also weder angenommen noch abgelehnt? soll es den nicht mehr geben?

**Comment by Helene0** [comment]
wie wärs mit einem grauen default label das sagt "offen"
