### ISSUE TITLE
Adding Texts and Renaming

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#368]
**As**
pupil

**I want**
to have useful texts and headline

**In order to**
understand everything correctly

**Dependencies:**

**Estimate:**

**Acceptance Criteria:**
- [x] Renamed "Anfrage stellen" in navbar in "Workshop anfragen"
- [x] replace Lorem ipsum on top of main page with: 
*Bist Du interessiert an IT-Systems-Engineering, Design Thinking oder Entrepreneurship? Dann bist Du hier bei uns genau richtig. Hier findest du spannende Camps und Workshops des Hasso-Plattner-Instituts für Schülerinnen und Schüler sowie Berufstätige, die eine Abwechslung zum normalen Alltag suchen. 
Schau doch mal bei uns vorbei!*
- [x] replace lorem ipsum on event overview page and in the corresponding section on the main page with:
*Hier findest du einen Überblick der kommenden Veranstaltungen am Hasso-Plattner-Institut. Beispielsweise können sich Schülerinnen und Schüler bei den Veranstaltungen der Schülerakademie gezielt über den Studiengang "IT-Systems Engineering" oder allgemein über das Informatikstudium und neue Technologien informieren.*
- [x] add the following text at the top of the request-page
*Wenn Sie einen Workshop am HPI durchführen wollen, füllen Sie bitte das folgende Formular aus. Die weitere Planung und Kommunikation wird über E-Mail erfolgen.*
- [x] on the main page: replace the text under "Workshop Anfragen" (everything over the button):
*Das HPI organisiert auch individualisierte Workshops, beispielsweise für Schülerinnen und Schüler, die besonders interessiert an Informatik sind oder für Unternehmen, die ihre Mitarbeiter weiterbilden möchte. Mit einer gewissen zeitlichen Flexibilität und etwas zeitlichem Vorlauf können wir meist alle Anfragen verwirklichen.*
- [x] remove "HPI Schülerklub" on main page (under events)

**Comment by julisa99** [comment]
@tom95 Zwar wurden die Texte von unserem Kunden genehmigt, aber bitte passe im Text an, dass einheitlich die Anreden entweder groß  oder klein geschrieben werden. Zurzeit ist leider mal ein "Du", dann aber woanders ein "du". Woanders ist plötzlich ein Wechsel vom Du zu Sie, wo dann "Sie" steht. Das scheint uns leider untergegangen zu sein.

**Comment by tom95** [comment]
As discussed with @julisa99 please update the texts accordingly, I can then copy them over. Otherwise, please close this issue again.
