### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#369]
**As**
user

**I want to**
see sound footer containing information about the web site

**in order to**
easily find main meta information .

# Dependencies

- Refs #352 (Imprint)

# Acceptance criteria

- The footer is resized to a smaller, well-looking size (wrapping the contend)

- The footer contains the copyright information (© 2017 Hasso-Plattner-Institut)

- The Companion Cube <3 text is deleted 

- The footer contains a link to the Imprint (Refs #352)

- The footer contains a link to the HPI website (https://hpi.de/)

- In order to simplify the adaption of the footer before hosting the website, the wiki should contain a description, where to adapt the contend of the footer. (Similar to Refs #352)

**Comment by tobiasduerschmid** [comment]
Wiki entry is here: https://github.com/hpi-swt2/workshop-portal/wiki/Imprint-Placeholder-Values
