### ISSUE TITLE
"Herr/Frau"-field doesn't get highlighted when it has errors

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#381]
<img width="1680" alt="bildschirmfoto 2017-01-20 um 00 57 51" src="https://cloud.githubusercontent.com/assets/7229585/22473777/3d5ddd00-e7da-11e6-8fb7-3ac9b0b9b836.png">

**Comment by julisa99** [comment]
@radscheit das hatte ich dir letztes Mal schon erzählt, kümmerst du dich zufällig darum schon?

**Comment by Baschdl** [comment]
@julisa99 Is this one reserved for your team?

**Comment by cmfcmf** [comment]
By the way: i had looked at this already and noticed that the error doesn't look like seen on the screenshot anymore. While it still isn't outlined in red it at least now displays an error message right below the field. This might actually be a sufficient fix for this bug.

**Comment by cmfcmf** [comment]
@bjrne please give feedback on whether the current state is sufficient:
![image](https://cloud.githubusercontent.com/assets/2145092/22596883/a2899be2-ea2d-11e6-9139-8e601de7781e.png)

**Comment by bjrne** [comment]
@cmfcmf Looks alright to me, but in the end thats up to our @hpi-swt2/product-owner-2016. I was just bringing it up :)

**Comment by cmfcmf** [comment]
Moved to `needs acceptance` then.

**Comment by hendraet** [comment]
:heart_eyes:
