### ISSUE TITLE
Umbenennung bei Anfrage erstellen

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#382]
**As** 
user

**I want to** 
be adressed even when I am not a student

**in order to** 
feel like i am at the right place

# Acceptance Criteria
- Feld heißt "Schule/ Organisation" anstelle von "Schule" auf "Anfragen erstellen" Seite

**Comment by tobiasduerschmid** [comment]
There is no "Schule" field on the request page
