### ISSUE TITLE
User "Meine Veranstaltungen" statt "Meine Bewerbungen"

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#383]
**As** 
user

**I want to** 
be able to find my Workshops and Requests

**in order to** 
have easy navigation

# Acceptance criteria

- "Meine Bewerbungen" is now called "Meine Veranstaltungen"

**Comment by bjrne** [comment]
Sollte das dann nicht korrekterweise "Meine Veranstaltungen" heißen, damit das nicht so denglisch ist?

**Comment by hendraet** [comment]
:100:
