### ISSUE TITLE
Anpassungen auf Eventdetailpage

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#385]
**As** 
user

**I want to** 
see relevant information for me only 

**in order to** 
have easy navigation

# Acceptance Criteria
- User (Pupil und nicht Eingeloggte) sollte Felder, die nicht von Orga ausgefüllt wurden, nicht sehen (zb." Kenntnisstand:             " und dann nichts danach, weil nichts eingetragen wurde)

- Warning mit langem Datumsbereich nur für Orga sichtbar

**Comment by hendraet** [comment]
:two_hearts:
