### ISSUE TITLE
Umbenennung und Anpassung auf "Profil erstellen" Seite

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#386]
**As** 
user

**I want to** 
be adressed correctly even if I am not a student

**in order to** 
not be confused

# Acceptance criteria
 - "Vorraussichtliches Abitur" is deleted from the profile (organizers have to add it to the custom application fields)
- The field "Schule" is deleted form the profile
- The field "Schule/Organisation" is added for each application
- The option "Schule anzeigen" on the [print name badges page](http://workshop-portal-dev.herokuapp.com/events/1/badges) is replaced with "Schule / Organisation anzeigen"
- Please search for "Schule" in the project folder and replace other occurrences, if present.

**Comment by hendraet** [comment]
:heart:
