### ISSUE TITLE
Anpassungen auf "Bewerbung erstellen" Seite

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#387]
**As** 
user

**I want to** 
have an easy user interface of the application 

**in order to** 
have a great user experience

# Acceptance Criteria
- The check boxes "vegetraisch" and "vegan" are shown in one row. 
- The Checkbox "Allergien" is deleted, because the text field is enough

**Comment by cmfcmf** [comment]
PR: #456

**Comment by hendraet** [comment]
:1st_place_medal:
