### ISSUE TITLE
Anpassungen auf "Bewerbung abgesendet" Page

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#388]
**As** 
user

**I want to** 
have a good overview over my data

**in order to** 
know if i entered right information 

# Acceptance criteria

- [x]  beide Informationsbalken über der Überschrift
-  [ ] Motivationsschreiben nicht vollständig anzeigen, sondern ersten 3 Sätze und dann "weiterlesen" um das ganze Schreiben aufzuklappen

- [ ] Use not more than three different text sizes. 

- [ ] vertical spaces are introduced between the different entries

- [ ] The order of entries is: Motivationsschreiben, Schule / Organiasation, Klassenstufe, Mit welchen Programmiersprachen hast du bereits Erfahrungen gesammelt?:, Essgewohnheiten, Allergien, Telefonnummer für Notfälle, Anmerkungen 
- [ ] larger vertical spaces are introduced between semantically different entries (over "Schule / Organisation" and "Essgewohnheiten")

**Comment by hendraet** [comment]
@Philipp-Bode Die Informationsbalken sind schon drin, oder?

**Comment by philipp-bode** [comment]
Aye, die Balken sind schon drüber
