### ISSUE TITLE
Complete the "Anfrage"-detail page

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#392]
**As**
organizer

**I want to**
see all information of a request

**In order to**
be able to correspond with the requesting person and get the details about the request. 

## Acceptance criteria:
- When a Alice created a request, organizers see all information, Alice entered in the form "Anfrage-stellen"-Page on the "Anfrage"-detail page. Currently for example missing: E-Mail, Orga/Firma, ...
- The email address is linked with a Mail-to-Link in order to simplify writing an E-Mail.

**Comment by julisa99** [comment]
@MasterCarl Zeitrahmen wird nicht angezeigt auf der detail-page

**Comment by MasterCarl** [comment]
Fixed in #472
