### ISSUE TITLE
Remove max participants infinity

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swt2/workshop-portal#399]
Instead of infinity a large number should be sufficient

**Comment by bjrne** [comment]
So this would consist of removing and adapting the following: (Feel free to edit and adapt)
- [x] database: remove field (event->unlimited)
- [x] remove modification from getter & setter for max_participant
- [x] remove translation for infinity stuff from the locales
- [x] remove checks for infinity in views (especially event show page / applicants overview)
- [x] remove checkbox for infinity from event creation/editing
- [x] remove assignments of max_participants to infinity (e. g. in tests)
- [x] remove it from event params in event controller
- [ ] ?

**Comment by ekrebs5** [comment]
now part of #16
