### ISSUE TITLE
US_2.5: Application Form (additional Information)

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#40]
**As**
Organizer 

**I want**
pupils to enter additional information (which may differ from camp to camp) in an application

**in order**
to know why they want to participate, if they have allergies, etc.

This additional data may be:

- Klassenstufe *
- „Wie hast Du von uns erfahren?“ *
- Motivationsschreiben *
- Programmiersprachen  * 
- Telefonnummer für Notfall während des Camps *
- Vegetarisch *
- Vegan *
- Allergien vorhanden *
- Falls Allergien vorhanden welche?
(* = mandatory fields)

**Estimate:** 3

**Acceptance Criteria**
- A user cannot submit a form without completing all the mandatory fields
- Mandatory fields are marked as mandatory
- An error will be displayed if the not all mandatory fields are completed
- The error highlights which fields aren't completed
- The entered data is stored in the (application-)database
- The "fields" for "Vegan", "Vegetarisch", "Allergien vorhanden" are checkboxes
- The fields for "„Wie hast Du von uns erfahren?“, "Motivationsschreiben" and "Programmiersprachen" are text areas (#13)
- The rest of the fields are "normal" input fields

**Comment by j3sk1n** [comment]
Estimate: 3

**Comment by hendraet** [comment]
Checkbox are displayed next to title
User and Workshop is set automatically

**Comment by Square0ne** [comment]
Klassenstufe muss integer

**Comment by Square0ne** [comment]
@hendraet das 2. hat doch schon issue #15 @cmfcmf und @hefowe implementiert, oder?
