### ISSUE TITLE
US_4.16: Application confirmation 💰 5

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#41]
**As**
pupil 

**I want to**
get a confirmation email when I submitted my application 

**in order to**
 be sure, that it was submitted successfully.  

**dependency:** #40, ...

**acceptance criteria:**
- a mail is sent to the mail address which is registered to the user
- the mail says that the application was submitted, and for what the user applied:
 "Liebe[r] [Vorname] [Nachname],
du hast dich erfolgreich für die Veranstaltung [Veranstaltungsname] beworben. Deine Bewerbung wird von uns bearbeitet. Für den aktuellen Status deiner Bewerbung siehe unter "Meine Bewerbungen" im Portal" (Portal with Link to the start page).
Viele Grüße
das HPI-Workshop-Team
- mit den entsprechenden Zeilenumbrüchen!
- representative mail address

**Comment by julisa99** [comment]
Now, it is for me:
"Liebe Lisa Ihde,\n\r du hast dich erfolgreich für die Veranstaltung Einführung in die Kunst der Gongakrobatik beworben. Deine Bewerbung wird von uns bearbeitet. Für den aktuellen Status deiner Bewerbung siehe unter "Meine Veranstaltungen" im Portal (http://workshop-portal-dev.herokuapp.com/applications)."

\n\r is wrong
and "Viele Grüße das HPI Workshop Team" is missed
additionally "Portal" should be the link and not the url in "(...)"

**Comment by julisa99** [comment]
Zeilenumbruchanstelle des Kommas nach "Viele Grüße" fehlt noch.
Bei mir wird nach "Status deiner Bewerbung" ein Zeilenumbruch gemacht (könnte auch an meinem Email-Tool liegen).
Optional Veranstaltungsnamen kursiv oder in Anführungsstrichen setzen.

**Comment by julisa99** [comment]
Push es auf den dev, dann kann ich es testen
