### ISSUE TITLE
Fehler beim inline Pdf bei Firefox beheben

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#413]
![grafik](https://cloud.githubusercontent.com/assets/8758907/22300292/4ec3062c-e327-11e6-98b9-95a5a0865585.png)

- [ ] Essgewohnheitenliste, Namensschilder und Teilnehmerliste öffnen im neuen Tab (target="_blank")
- [ ] Debug-Ausgabe rausnehmen (lib/pdf_generation/badges, die Zeile mit `puts`)

- [ ] Teilnehmerliste- und Essgewohnheiten-Button ausgrauen, wenn keine Teilnehmer existieren

**Comment by bjrne** [comment]
I'd rather tag this as bug/regular story. Technical debt is more a tag for developer related stuff that doesn't directly impact functionality (e.g. things you shouldn't have to worry about as a PO).
