### ISSUE TITLE
US_4.5a: Eating habits & allergies 💰 2

### ISSUE THREAD

**Issue by pinussilvestrus** [hpi-swt2/workshop-portal#42]
**As**
pupil

**I would like to**
edit my eating habits & allergies in my user area and in the registration

**in order to**
show the organizer my eating habits & allergies

**Acceptance Criteria**

- input field for eating habits (vegan, vegetarian...)
- input field for allergies

**Comment by radscheit** [comment]
@julisa99 Please provide a list of common eating habits you want to work with.

**Comment by radscheit** [comment]
@julisa99 ?

**Comment by julisa99** [comment]
"Ich esse alles, was Mama kocht ;)", "Vegan", "Vegetarisch", "Frutarier" und "Rohköstler"

**Comment by radscheit** [comment]
Danke 👍

**Comment by tobiduer** [comment]
@radscheit: Das Essverhalten wurde bereits implementiert. Die dazugehörige US ist US_2.5 (#40). Braucht nicht weiter bearbeitet werden. Schnapp dir was anderes.

**Comment by radscheit** [comment]
@tobiduer Das ist aber sehr ärgerlich. Immerhin war ich bereits fast fertig. Ich fände es schön, wenn ein wenig respektvoller mit meiner Zeit umgegangen werden würde.
