### ISSUE TITLE
Teilnehmerliste-Button

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#420]
- [ ] Button erscheinen lassen, nachdem die Zusagen verschickt wurden, an der Stelle, wo vorher der "Zusagen verschicken"-Button war
- [ ] Farbe des Buttons auf blau oder orange ändern (beides mal ausprobieren und gucken was besser zum Rest passt)
![420](https://cloud.githubusercontent.com/assets/6051384/22333825/46cb8244-e3d8-11e6-9c80-3be6e8e31814.gif)

**Comment by radscheit** [comment]
@h0rnyc0rny @julisa99 Difficult to solve, because the "Zusagen verschicken"-action doesn't work properly. Calling this action results in an email draft without any recipients... How to go on with this?

**Comment by radscheit** [comment]
@tom95 Hej Tom, @julisa99 said that you are about wo work on the confirmation mail issue, right?

**Comment by ekrebs5** [comment]
We ( @querenker @aloeser @frederike-ramin ) are currently reworking the mail structure and the visibilty of the email buttons as part of #244 and #242.
Maybe this should be done after that?

**Comment by aloeser** [comment]
@radscheit it should be fixed now. Just in case its not, try adding status=acceptance (or =accepted, if you dont wanna merge dev atm) to the email url

**Comment by tobiasduerschmid** [comment]
@radscheit: This issue only contains changing the positing and the color of the button. The visibility is done yet.

**Comment by julisa99** [comment]
@radscheit okay, let's go! :)

**Comment by radscheit** [comment]
@julisa99 @tobiduer @ekrebs5 Thanks for your help.
