### ISSUE TITLE
Gruppenfarben-Auswahl verbessern

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#421]
- [ ] Nicht jedes Mal neu laden, wenn eine Gruppenfarbe ausgewählt wurde
- [ ] Farben auswählen über ein Bearbeiten-Button und dann einmal speichern durch Speicher-Button, für beides kleine Symbole nutzen, die oben im Spaltentitel immer angezeigt werden.

**Comment by Blaidd-Drwg** [comment]
Would it also be ok if the groups were saved using AJAX? That way the groups would be automatically saved after selection, but the page would not need to reload.

**Comment by julisa99** [comment]
yes

**Comment by julisa99** [comment]
yes

**Comment by tobiasduerschmid** [comment]
@hpi-swt2/product-owner-2016: I changed the priority to high, because this US will improve the experience of the demo.

**Comment by tom95** [comment]
Directly writing any changes will drastically decrease the workload required for this US (and probably also increase the user experience, since it's already two clicks you have to do to commit any change and introducing a third and fourth will probably not make that better)
