### ISSUE TITLE
Example Workshops On Request Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#426]
**Acceptance Criteria**
- [ ] carousel ui element on request page directly under intro text
- [ ] at least 3 elements (dummy texts can be found [here](https://hpi.de/open-campus/schuelerakademie/projekttage.html))

**Comment by bjrne** [comment]
As @radscheit pointed out, this looks like a duplicate of #319. @hpi-swt2/product-owner-2016 ?

**Comment by hendraet** [comment]
Was a duplicate
