### ISSUE TITLE
Stock Photo Selection (Event Creation)

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#428]
**As**
organizer

**I want to**
choose a photo for an event during its creation

**in order to**
customize the visual appearance of the event. 

**Dependency:** #320 

**Acceptance Criteria**

It's dangerous to go alone. Take this:
![image_upload](https://cloud.githubusercontent.com/assets/16731894/22504170/586eec1a-e875-11e6-9823-60c78301d5c3.png)

- [x] When an organizer creates an event, he / she can choose one photo for the event out of 5 stock preview images
- [x] The stock photo selection is directly located directly below the image upload
- [x] When an organizer clicks on the box, the system should set the preview image displayed in the box as preview image for the event (the image which is displayed on event overview page)
- [x] the preview image will then be displayed in the box next to the explaining text
- [x] after an image is saved by click on the according button the the preview image will be updated
- [x] When an organizer creates an event, one of the stock photos should be selected as default image in order to ensure, that in all cases, one photo is selected. 
- [x] Each data base entry of the sample data has one associated photo. 
- [x] Wenn ein Bild hochgeladen wurde, wird dieses gespeichert. Zwischendurch kann ein Stock-Photo ausgewählt und als Preview gesetzt werden. Durch einen Klick auf den entsprechenden Button kann das bereits hochgeladene Bild aber wieder ausgewählt werden. (I wrote this in German to avoid confusion due to my poor english)
- [x] when a stock photo is selected but not saved it will have a colored border

**Images:**
[stock.zip](https://github.com/hpi-swt2/workshop-portal/files/735075/stock.zip) (Be careful there might be malware in it)

**Comment by bjrne** [comment]
@hpi-swt2/product-owner-2016  Today our team decided that we want two pictures per event, one for the preview and one for the title. Please specify the wanted UI for setting these more precisely, maybe even with a wireframe? 🙂 
And could you also specify in which cases you'd like a warning or hints before overwriting existing pictures with stock fotos? (The editing user might not be the creator and might not have access to all fotos to reupload them again)

**Comment by hendraet** [comment]
@bjrne I will rework this US and draw a wireframe

**Comment by tobiasduerschmid** [comment]
@hendraet: I started improving this US.

**Comment by tom95** [comment]
@hpi-swt2/product-owner-2016 as shown in the description of this issue, this has #320 as a dependency, so it can't be in ready

**Comment by tobiasduerschmid** [comment]
@tom95: Beside some minimal UI improvements, #320 is implemented now. So this US is ready now :)

**Comment by hendraet** [comment]
:kissing:
