### ISSUE TITLE
Multiple UI Improvements

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#430]
**Acceptance Criteria**
- [x] login and register box have the same height 
- [ ] button in "Hochladen-Banner" should be smaller (xs -tag)
- [x] rename label "Über XX Tage" in "Umfang: XX Tage"

**Comment by tobiasduerschmid** [comment]
@hefowe: Could you please check the "Hochladen-Banner" ?

**Comment by cmfcmf** [comment]
I suppose you mean @hendraet?

**Comment by tobiasduerschmid** [comment]
Yes :D

**Comment by hendraet** [comment]
:purple_heart:
