### ISSUE TITLE
Application Page For Hidden Events

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#432]
**Dependency**: #271 

**Acceptance Criteria**
- [x] application form for hidden events should only include "Programmierkenntnisse, Allergien/Essgewohnheiten, Anmerkungen" (or whatever the last field is called)
- [x] should nevertheless include custom fields if specified
- [x] rename "Bewerbung erstellen" button: "Anmelden"
- [x] Show "application" under "Meine Bewerbungen"

**Comment by bjrne** [comment]
@hpi-swt2/product-owner-2016 Shouldn't they have custom fields as well?

**Comment by hendraet** [comment]
@bjrne Sorry for not specifying it in the first place. I took it as given

**Comment by bjrne** [comment]
No problem, I was just confused because there was this 'only [...]' .

**Comment by nilsthamm** [comment]
@hpi-swt2/product-owner-2016 i think despite of the button name, all of it is already implemented

**Comment by hendraet** [comment]
@nilsthamm There was an "only" missing.

**Comment by nilsthamm** [comment]
@hendraet i guess the title of the page should also be changed to "Anmeldung erstellen"

**Comment by hendraet** [comment]
:exclamation:
