### ISSUE TITLE
Reduce page loading time

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#433]
Can someone please figure out why our page is often loading 7+ seconds when initially loaded?

**Comment by MasterCarl** [comment]
When does this happen? I analyzed the loading performance in Chrome and the page was complete after about 700ms, even with 5x CPU throttling.

**Comment by radscheit** [comment]
@bjrne It has to render the less, css and js files on initial load. I think in an dev env we have to live with that - aggressive caching is our enemy. In production we have several options to work with caching, depending on the env itself.

**Comment by Baschdl** [comment]
It's pretty fast. ~600ms + ~500ms loading of pictures with emptied cache
![speed](https://cloud.githubusercontent.com/assets/3034832/22525441/7743bfd8-e8c7-11e6-9046-9c56ba5b1af2.png)

**Comment by julisa99** [comment]
Hat sich erledigt, oder?

**Comment by bjrne** [comment]
Looks like it. I experienced different times a week ago. Seems fine now.
