### ISSUE TITLE
Epic_3.1: Participant Selection Process

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#44]
Coach and organizers select applications of pupils together and send emails to the pupils

**Comment by cmfcmf** [comment]
👍

**Comment by tobiduer** [comment]
![activity](https://cloud.githubusercontent.com/assets/16103359/20359566/c1379a7a-ac30-11e6-8f3b-a17bfedc3b15.jpg)

**Comment by tobiduer** [comment]
![usecases](https://cloud.githubusercontent.com/assets/16103359/20360228/34aa1102-ac33-11e6-945d-9da4b793d978.jpg)

**Comment by tobiduer** [comment]
![activity](https://cloud.githubusercontent.com/assets/16103359/20379710/07bd7966-ac9e-11e6-9c11-4ff8072372d3.jpg)
![usecases](https://cloud.githubusercontent.com/assets/16103359/20379711/07dc7c12-ac9e-11e6-9b33-71d79dbf3cdf.jpg)

**Comment by tobiduer** [comment]
![usecases](https://cloud.githubusercontent.com/assets/16103359/20379711/07dc7c12-ac9e-11e6-9b33-71d79dbf3cdf.jpg)
