### ISSUE TITLE
US_1.7: Additional Information 🍪7

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#46]
**As** 
organizer 

**I want to** 
be able to add the name of the external organisation, if there is one (Veranstalter), and the knowledge pupils need to participate (Kenntnisstand), but only if needed

**in order to** 
choose what information is relevant for pupils

**7 🍪**

- [x] The fields "Veranstalter" and "Kenntnisstand" are optional and also appear as such.
- [x] I can enter text in those fields and save it

**Comment by MasterCarl** [comment]
See merged pull request https://github.com/hpi-swt2/workshop-portal/pull/71

**Comment by MasterCarl** [comment]
Also https://github.com/hpi-swt2/workshop-portal/pull/80
