### ISSUE TITLE
US_1.9: Camp/Workshop Overview Page 🍪8

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#47]
**As** 
organizer
 
**I want to** 
have an overview page with all workshops/camps that were created and their status 

**in order to** 
see which camps are not published yet, and which are

**10 🍪**

Acceptance criteria:
- [ ] I have an overview table with the name of the event, the eventkind (WS, Camps), the timespan, and the status (saved or published)
- [ ] Timespan begins with first date and ends with last date of the event

**Comment by bjrne** [comment]
- [ ] Rename "active"-field to "published"

**Comment by MasterCarl** [comment]
It might be useful to delete the field "active" to avoid confusion. My implementation for drafts uses the field "draft"

**Comment by LeaGe** [comment]
@Helene0 please review :)
