### ISSUE TITLE
Resizing of headings (mobile phones)

### ISSUE THREAD

**Issue by Baschdl** [hpi-swt2/workshop-portal#474]
# User Strory

**As**
mobile user

**I want to**
resize the heading to fit the screen

**in order to**
be able to easily read the text without moving the 

# Current State (before fix)

The headings are not resized on mobile phones

![website-1](https://cloud.githubusercontent.com/assets/3034832/22525103/39498664-e8c6-11e6-9413-7ade944c9871.png)
![website-2](https://cloud.githubusercontent.com/assets/3034832/22525093/307d3aa8-e8c6-11e6-9b62-b21700240bb3.png)

**Comment by bjrne** [comment]
@hpi-swt2/product-owner-2016
