### ISSUE TITLE
Login page is visually discomforting

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#476]
<img width="1680" alt="bildschirmfoto 2017-02-01 um 21 49 06" src="https://cloud.githubusercontent.com/assets/7229585/22525687/82e0e2fc-e8c8-11e6-8a34-24512410cf72.png">

**Comment by cmfcmf** [comment]
You Safari users :P Cannot reproduce this in Chrome or Firefox.
![image](https://cloud.githubusercontent.com/assets/2145092/22525770/f39b7a8e-e8c8-11e6-895b-3ddf48bb3351.png)

I don't really like the equal height boxes anyway, but it was part of the user story. A solution could be to simply remove that requirement :)

**Comment by hendraet** [comment]
:yellow_heart:
