### ISSUE TITLE
UI of start page

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#477]
**As**
user of the portal

**I want to**
see a well-looking sound start page 

**in order to**
get a good first impression of the portal. . 

# Acceptance criteria

- [x] "Workshop portal" is renamed to "Workshop Portal"
- [x] The distance of the p of "portal" and the H of "HPI" is larger

**Comment by bjrne** [comment]
Do you mean the vertical space @hpi-swt2/product-owner-2016  ?
It's a bit unclear, but the mentioned letters are not neighbors horizontally.
<img width="475" alt="bildschirmfoto 2017-02-02 um 16 52 05" src="https://cloud.githubusercontent.com/assets/7229585/22556677/543d07d2-e968-11e6-9518-e673da3ad15c.png">

**Comment by bjrne** [comment]
After #484 it now has different distances between the lines. I don't feel like normal users would notice but to me it still looks weird.

**Comment by hendraet** [comment]
@bjrne @hefowe It's true. It looks off. Why is there a difference in line spacing? 
Would be great if line spacing would be the same.

**Comment by hefowe** [comment]
@hendraet The line spacing is different because we use a div spacer instead of a br tag. I can change it back to a br tag, but then the lowercase 'd' overlaps the lowercase 'p' a little bit (the top of 'd' is on the same height as the end of 'p').

**Comment by tobiasduerschmid** [comment]
@bjrne: We did not move the card to ready. Therefore the ACs were not well elaborated. But yes, we mean the vertical distance. 

@hefowe: I like the current visual look :) :+1:

**Comment by bjrne** [comment]
@tobiduer It was still mentioned in #484 so that didn't cross my mind. Alright then :)

Did you also test various screen widths? If you didn't, please do since the heading varies a lot with changes in the overall width.

**Comment by tobiasduerschmid** [comment]
Yes. It looks good with various screen widths.
