### ISSUE TITLE
If event end date is today event isn't shown in event list

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#491]
^this

**Comment by hendraet** [comment]
@Philipp-Bode Is it your fault that the event still doesn't show on the main page?

**Comment by philipp-bode** [comment]
I fixed the scope that was used for the event-index list, apparently the main page does not use that scope. Am on it.

**Comment by bjrne** [comment]
@tom95 Maybe?

**Comment by hendraet** [comment]
:revolving_hearts:
