### ISSUE TITLE
Placeholder not replaced in application confirmation email

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swt2/workshop-portal#492]
> Hallo,
>
> Du hast dich erfolgreich für  **{{semimar_name}}** beworben. Deine Bewerbung wird jetzt bearbeitet. Für weitere Information besuche das Workshop Portal. Viele Grüße, das HPI Workshop Team

https://github.com/hpi-swt2/workshop-portal/pull/453

**Comment by cmfcmf** [comment]
@hpi-swt2/product-owner-2016

**Comment by hendraet** [comment]
@cmfcmf We will move this to a seperate story.

**Comment by cmfcmf** [comment]
Can we leave this open until such a story exists, please?

**Comment by tobiasduerschmid** [comment]
Currently the email looks like "Lieber {{first_name}} {{last_name}},\n\r du hast dich erfolgreich für die Veranstaltung {{seminar_name}} beworben. Deine Bewerbung wird von uns bearbeitet. Für den aktuellen Status deiner Bewerbung siehe unter "Meine Veranstaltungen" im Portal ({{event_link}})."

If this issue will not be implemented. @hendraet: Is this issue a duplicate now? If yes, you can remove it. If no, it should be moved out of the PO acceptance column.

**Comment by Blaidd-Drwg** [comment]
My bad, I missed the wrong usage of placeholders during the review. Fixing it right now.

**Comment by Blaidd-Drwg** [comment]
Once more, with feeling.

**Comment by julisa99** [comment]
Now, it is for me:
"Liebe Lisa Ihde,\n\r du hast dich erfolgreich für die Veranstaltung Einführung in die Kunst der Gongakrobatik beworben. Deine Bewerbung wird von uns bearbeitet. Für den aktuellen Status deiner Bewerbung siehe unter "Meine Veranstaltungen" im Portal (http://workshop-portal-dev.herokuapp.com/applications)."

\n\r is wrong
and "Viele Grüße, das HPI Workshop Team" is missed
