### ISSUE TITLE
Adjust Sample Data

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#500]
**As**
PO 

**I want to**
have suitable sample data

**in order to**
support the presentation

# Acceptance criteria

- The @hpi.de dummy accounts have the german translation of the role as last name

- Instead of using the Gongakrobatik event twice, a new event (HPI Sommercamp) should be created, whose deadline is over.

**Comment by bjrne** [comment]
If it helps, have a look at the branch `adjust_sample_data`.

**Comment by tobiasduerschmid** [comment]
@nilsthamm: The build of your PR is still broken. #519

**Comment by tobiasduerschmid** [comment]
Can you add line breaks for the event description?

http://workshop-portal-dev.herokuapp.com/events/7

**Comment by nilsthamm** [comment]
yes, i guess it would also be useful for the other events?!

**Comment by hendraet** [comment]
:metal:
