### ISSUE TITLE
Remove past date validations

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#505]
After discussion with @tom95 we decided we no longer need these validations since it is unnecessary code overhead and prevents past events to be edited.

**Comment by blackknight75** [comment]
@bjrne I would like to try this. Could you share more details about which models you want to do this on?

**Comment by bjrne** [comment]
Hey @blackknight75,
I love that you want to help! This is a project from a course from last semester and some students are trying to further expand the project this term in their free time. We don't have a perfect plan for everything yet, so things may be a little uncoordinated or unspecified since we also happen to basically live on the same campus and meet to plan things regularly. If you want to know more, send me a mail or something :)

This issue was intended for removing some validations in the `event`-Model, especially the one that checks wether an event is in the future. However depending on our other plans for the draft state of an event there may be more obsolete validations or new ones that I can't think of for now.
