### ISSUE TITLE
"In Bearbeitung" State of Applications.

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#507]
**As** 
organizer

**I want to**
hide the temporary state (when an organizer pushed the accept / reject button before sending the emails) of an applicant from the user

**in order to**
be able to change it without the applicant noticing the change. 

# Acceptance criteria

- When the event is in the [selection phase](https://github.com/hpi-swt2/workshop-portal/issues/233), the applicant should see "in Bearbeitung" as [state of the application](http://workshop-portal-dev.herokuapp.com/applications)

- Coaches should see the state chosen by organizers (accepted / rejected / alternative)

**Comment by ekrebs5** [comment]
@tobiduer what do coaches see? pending are the "actual" thing (even if actual is temporary and they can't click on it)?

**Comment by tobiasduerschmid** [comment]
@ekrebs5: Coaches should see the state chosen by organizers (accepted / rejected / alternative)

**Comment by hendraet** [comment]
:couplekiss_man_man:

**Comment by hendraet** [comment]
@hefowe Sorry for reopening this but there is bug. If a participant is marked as "angenommen" he sees the warning: please upload letter of agreement

**Comment by hendraet** [comment]
@hefowe nvm this seems to be part of #555
