### ISSUE TITLE
XSS attack via custom MarkdownRenderTruncate

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swt2/workshop-portal#511]
# Steps to reproduce
- login as organzier or admin
- edit the event description and include malicious content, i.e. 
```
# Hallo
<script>alert('Get cheap drugs from http://hpi.de.')</script>
```
- go to http://workshop-portal-dev.herokuapp.com/events
- enjoy :) 

# Further thoughts
While this currently only affects organizers and admins, it could also affect other people if the [`MarkdownRenderTruncate`](https://github.com/hpi-swt2/workshop-portal/blob/d7e3194b7788c1c377a2ca7a8e81f527efeb5ec6/app/helpers/application_helper.rb#L6) is ever used for user / guest input.
Also, I was really disappointed when I found out that the session cookie is `httponly`, so I couldn't steal it :(
Of course, you can still use the JavaScript injection to do funky stuff.

@hpi-swt2/product-owner-2016

**Comment by LeaGe** [comment]
i would like to try fixing this. But I'll probably need help. @cmfcmf do you think, we could do pair programming on this?

**Comment by cmfcmf** [comment]
> i would like to try fixing this. But I'll probably need help. @cmfcmf do you think, we could do pair programming on this?

Glad to hear you want to try, looks like I won't be in Potsdam that much to do pair programming next week though 😕
