### ISSUE TITLE
Downloading ANY file on the host machine vulnerability

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swt2/workshop-portal#514]
# Steps to reproduce
- Login as organizer or admin
- Create an event called `a`
- Visit http://localhost:3000/events/EVENTID
- Upload an image as material
- Verify the image was uploaded and the material is displayed
- Rename the event to `a/../../../../../../../etc/` (this path works well for the Vagrant configuration, experiment with other paths if you don't use Vagrant)
- Visit http://localhost:3000/events/EVENTID
- Browse the list of files inside the machines `/etc` folder
- Download the `passwd` file
- Start hacking :)

![image](https://cloud.githubusercontent.com/assets/2145092/22618260/f00faad2-ead7-11e6-9842-073bf321532a.png)

# Further thoughts
- Using the event name in the `material_path` method is super insecure. Attackers who are able to change the event name can easily use this to traverse the whole file system.
- This also means that an attacker who has access to the database automatically has access to the whole file system.

@hpi-swt2/product-owner-2016

**Comment by hendraet** [comment]
:love_letter:
