### ISSUE TITLE
Draft actions are misleading on event creation page

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#520]
When using the indicative form of verbs on buttons, user might expect something to happen. I'd prefer a more passive version. Moreover, when finally clicking on the create button on the bottom, it is not obvious what will happen since it says "Erstellen" independently of my choice. @hpi-swt2/product-owner-2016 

<img width="400" alt="bildschirmfoto 2017-02-04 um 22 45 32" src="https://cloud.githubusercontent.com/assets/7229585/22621799/1d91e732-eb2c-11e6-8246-09518b484584.png">

**Comment by corinnaj** [comment]
Is this less misleading?  
Creating a new event:
![screenshot from 2017-06-11 18-46-55](https://user-images.githubusercontent.com/14113727/27012748-c782d3ec-4ed6-11e7-8835-2d7aca55ef49.png)
Updating a draft:
![screenshot from 2017-06-11 18-47-26](https://user-images.githubusercontent.com/14113727/27012750-d70397c0-4ed6-11e7-9156-6a1fbe922b26.png)

**Comment by bjrne** [comment]
I like it. I'd still switch the buttons in one of them so publishing and drafting occur in the same position. I'd also suggest using grey for "save draft again" when updating an existing draft and call it "Entwurf aktualisieren". But I already like it a lot more than the version with the weird radio buttons.
