### ISSUE TITLE
Forced to send rejections emails even when no applicants were rejected

### ISSUE THREAD

**Issue by Blaidd-Drwg** [hpi-swt2/workshop-portal#525]
**As**
organizer 

**I want**
the event to switch to execution, event if no applicant was rejected

**in order to**
ensure correctness of the system.

# Dependencies

- Can interfere with #526 (Rejection Mail for alternatives)

# Acceptance criteria

- All of #418 

- When the organizer accepts all applicants and send the acceptance mail, then the event should switch to [execution state](https://github.com/hpi-swt2/workshop-portal/issues/233)

# Notes

The phase of the event doesn't change to `execution` if no rejection emails have been sent. As a consequence, the participant list button is not displayed.

![screenshot from 2017-02-05 01-25-51](https://cloud.githubusercontent.com/assets/6051384/22622729/2ce6abac-eb43-11e6-96f8-9c04c876ae7d.png)

After sending a "rejection email" to a bogus address, the event switches to `execution` and I can go back to organizing stuff.

![screenshot from 2017-02-05 01-26-37](https://cloud.githubusercontent.com/assets/6051384/22622758/4a2386ee-eb44-11e6-997e-96fc74fa402b.png)

@hpi-swt2/product-owner-2016

**Comment by tobiasduerschmid** [comment]
@ekrebs5: It works well. Currently, Nachrücker are not handled as rejected applicants. This means, that when I do not have rejected applicant, but Nachrücker, the "Absagen verschicken" Button can not be pushed. I guess, you will implement this in #526?

**Comment by ekrebs5** [comment]
yes, I think that would be part of #526
