### ISSUE TITLE
Rejection mail for alternatives

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#526]
**As**
organizer 

**I want to**
send rejection mails to alternatives (Nachrücker)

**in order to**
handle them like rejected applicants.

# Dependencies

- Can interfere with #525 (Transition from Selection to Execution when no rejection mails need to be send)

# Acceptance criteria

- When the organizer pushes "Absagen verschicken" button, the list of rejected applicants and alternatives are used as receivers of the email.

- When there are no rejected applicants, but Nachrücker, it should be possible to send letters of rejection (See #525 and #418)

**Comment by ekrebs5** [comment]
For developers:
- update the has_rejected_participants_without_status_notification? function in event to also include alternatives
