### ISSUE TITLE
US_3.14: Send Emails

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#55]
**As**
organizer

**I want to**
easily send emails out of the workshop portal

**in order to**
save time and keep the portal self-contained. 

**estimation: 40**

### UI
- [x] create generic reusable email-form
- [x] create new email view according to Epic 3.2 (including the generic email-form)
- [x] substitute modal with the email view
- [x] connect UI with technical infrastructure

### technical infrastructure
- [x] create fake E-Mail address
- [x] set default sender address
- [x] create generic mail template
- [x] allow multiple recipients
- [x] send E-Mails
- [x] store gmail credentials
- [x] tests
- [x] answer to field
- [x] documentation
- [x] refactor tests

## Notes

- The customers prefer to send from a generic email address of the workshop portal with a customized answer-to email address. 

## Acceptance criteria 

- The view for sending emails contain a "From"-field for entering the sender email address.

- The entered sender email address is validated in terms of `name"@"[subdomains"."]domain"."topLevelDomain`

- When the user hits the send button, the email is sent to the receivers and received within at most 30 minutes. 

- The user can choose between inserting the selected receivers in the "To" or "BCC" field.

- There can be many receivers specified. The user gets visual response for the separation of receivers email addresses. 

- Receivers are automatically entered when the organizer used the send-acceptance-mails-button or the send-rejection-mails-button. Please instruct the other teams how to use this feature for other use cases. 

- Emails are not classified as junk by usual spam filters.

- If passwords are stored persistently, they are stored encrypted

- The solution is easy to use as specified in the QAS below. 

- Emails should support multi-line-contend 

### Quality Attribute Scenario for Usability 
<img width="626" alt="email_req" src="https://cloud.githubusercontent.com/assets/16103359/20543528/7a90e3da-b106-11e6-9a7f-29b957ef3c76.png">

[As PDF](https://github.com/hpi-swt2/workshop-portal/files/607663/Email_req.pdf)

**Comment by tobiduer** [comment]
See: https://launchschool.com/blog/handling-emails-in-rails

**Comment by tobiduer** [comment]
Belongs to Epic_3.2: Emails (Refs #57)

**Comment by Baschdl** [comment]
A possibility mentioned by @Raandom could be [SendGrid](https://sendgrid.com). It's a "transactional email delivery and management service" (wikipedia), but I think it doesn't fit our needs.

**Comment by tobiduer** [comment]
@Baschdl: Why do you think, it doesn't fit our needs?

**Comment by Baschdl** [comment]
@hpi-swt2/team-d-16 There is also a free subscription: "Send 12,000 emails per month and store 2,000 contacts for free.". But to whitelist our domain we need a dedicated ip address, which is only available with a pro subscription.
It doesn't fit our needs because every sender mail domain must be whitelisted and we would conflict with e.g. the HPI infrastructure (SPF (Sender Policy Framework)...) when we do this.

**Comment by tobiduer** [comment]
The sender field for "answer to" is missing in the UI

**Comment by tobiduer** [comment]
# Feedback

When I enter a multi line contend in the UI, the send email does not have the new lines.

**Comment by Baschdl** [comment]
@tobiduer Did you accept this user story?
