### ISSUE TITLE
Application Check Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#550]
**Check out branch: new-check-page**

**Acceptance Criteria**

- [ ] should look like this (when letter successfully uploaded):
![checkpage_hochgeladen](https://cloud.githubusercontent.com/assets/16731894/22693386/58cd5926-ed43-11e6-9069-fc32d9c7c9bb.png)
- [ ] should look like this (when letter not yet uploaded but needed):
![checkpage_warnung](https://cloud.githubusercontent.com/assets/16731894/22693385/58b559b6-ed43-11e6-8a56-b278a117f500.png)
- [ ] display data as shown on the pictures above
- [ ] make sure Upload is not displayed when no letter is needed (yet)

**Comment by hendraet** [comment]
@tom95 pls add branch where you stored your changes

**Comment by LeaGe** [comment]
@hendraet why is there an option to upload a letter if it's not needed (example 2)

**Comment by hendraet** [comment]
Well...

**Comment by LeaGe** [comment]
@hpi-swt2/product-owner-2016 there is now a version in the code, that displays "Datei hochgeladen" and not "Einverständniserklärung hochgeladen am ..." which one is wanted by you?
