### ISSUE TITLE
Show "Einverständniserklärung hochladen" after acceptance only

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#555]
**As**
applicant

**I want to**
see the feature for uploading the letter of agreement only when I am accepted

**In order to**
focus on the current task.

# Acceptance criteria

- The text "Bitte lade deine Einverständniserklärung für "Musterworkshop" hoch." with the corresponding file upload is shows after sending the acceptance mails for accepted applicants only.

**Comment by hendraet** [comment]
@Fabian-Sommer please make sure that the user only sees this when he is accepted and "Zusagen/Absagen" are already sent

**Comment by ekrebs5** [comment]
already implemented
