### ISSUE TITLE
US_2.7: Application Status Overview

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#56]
**As**
pupil

**I want to**
have an overview over my applications and what their status is

**In order to**
manage my applications more easily

**Dependency:** #12, #45, #18

**Estimate:** 8

**Acceptance criteria**
- The view can be found via an entry in the dropdown in the "user-tab"
- page should look like this
![selection_013](https://cloud.githubusercontent.com/assets/16731894/20532900/ef35e67a-b0db-11e6-82e2-6e4fc772ee85.png)

- necessary elements:
  - title of event 
  - status ("angenommen", "abgelehnt", "In Bearbeitung" "Beworben")
  - edit-button
- status "Beworben" is shown before the deadline
- edit button is only shown before the deadline
- status "In Bearbeitung" is shown after the deadline
- status "Angenommen/Abgelehnt" are shown if application is accepted/rejected
- by clicking on title user is taken to site of the event

**Comment by JuliusCosmoRomeo** [comment]
edit application only works when logged in as admin (at least does not work when logged in as pupil)
