### ISSUE TITLE
Remove banner on event details page

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#564]
**As**
user of the portal 

**I do not want to**
see the banner for each event

**in order to**
be not disturbed by the pattern that does not match to the theme of the event.

**Comment by hendraet** [comment]
:cupid:

**Comment by hendraet** [comment]
Would be nice if there would be some spacing between headline and the rest

**Comment by tom95** [comment]
was addressed as part of a PR by @radscheit

**Comment by hendraet** [comment]
Noice
