### ISSUE TITLE
Redesign of startpage

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#572]
**Acceptance Criteria**
- [ ] startpage should look like this:
![startseite_hpi_hintergrund](https://cloud.githubusercontent.com/assets/16731894/22758563/7ae934b4-ee4f-11e6-832d-3b7f0ef2aa7f.png)
- [ ] bg image: https://hpi.de/fileadmin/user_upload/hpi/bilder/teaser_channels/architektur_campus/hpi_main_building_keyvisual_1020x420.jpg
- keep yellow color for the other boxes

**Comment by nstrelow** [comment]
@hendraet could you please provide an image with a higher resolution

This one works, but on a FullHD screen it doesn't look great

**Comment by MasterCarl** [comment]
@nstrelow Here's a higher resolution image: <https://hpi.de/fileadmin/user_upload/hpi/navigation/25_presse/25_bildmaterial/05_Fotos/10_campus/HPI_Hauptgebaeude_Tag_3054x2036.jpg>
