### ISSUE TITLE
Valid HPI email addresses in sample data

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/workshop-portal#603]
The sample data (`db/sample_data/users.rb`) currently contains the valid email address `admin@hpi.de`

![image](https://cloud.githubusercontent.com/assets/1652117/22790566/e5cdf93a-eee6-11e6-9674-008a7f0a9350.png)

**Comment by annkatrinkuessner** [comment]
additionally replace the valid e-mail addresses of Tobias and Hendrik.
