### ISSUE TITLE
Missing information in seeds.rb

### ISSUE THREAD

**Issue by bjrne** [hpi-swt2/workshop-portal#63]
As @radscheit already pointed out, db/seeds.rb is missing information to seed the database. Please add at least the required fields for a profile (`:first_name, :last_name, :gender, :birth_date, :email, :school, :street_name, :zip_code, :city, :state, :country`)

/cc @hefowe @cmfcmf @Philipp-Bode

**Comment by chrisma** [comment]
Maybe there could be a test that makes sure that `db/seeds.rb` can be loaded?
