### ISSUE TITLE
Add coding style guide

### ISSUE THREAD

**Issue by querenker** [hpi-swt2/workshop-portal#636]
I think [this community driven coding style guide](https://github.com/bbatsov/ruby-style-guide) looks promising. There is also good tool support for example [to comment automatically on style violations in GitHub pull requests](https://houndci.com/). Is it worth a try?

**Comment by annkatrinkuessner** [comment]
There's also [rubocop](https://github.com/bbatsov/rubocop) which is nice for code analyzation and also based on the ruby style guidelines. It is for example used by the openHPI project and is quite nice to use

**Comment by querenker** [comment]
@annkatrinkuessner  Thanks for the fast reply. I think Hound actually uses RuboCop (https://houndci.com/configuration#ruby).

**Comment by annkatrinkuessner** [comment]
btw: rubocop is already included in the gemfile. only a .rubocop.yml is missing to set houndci 
 and/or rubocop up :)

**Comment by querenker** [comment]
There is even a [codeclimate config](https://github.com/hpi-schuelerklub/workshop-portal/blob/dev/.codeclimate.yml#L17) which uses rubocop. After adding this repo to codeclimate it should be possible to integrate this analysis into the PR workflow (@bjrne you should have received a request for approval by email). Running rubocop locally should already work but there are a lot of offenses....
`222 files inspected, 4865 offenses detected`

**Comment by bjrne** [comment]
Actually I didn't @querenker, but that may have to do with m email settings. Sadly I didn't get any notification either. I tried my best on codeclimate, it should work now, but I'm not sure. It's also not so easy to filter on rubocop messages, we might want to change our config for this purpose.

**Comment by querenker** [comment]
@bjrne It seems to work 👍  At least PR #640 has a codeclimate check. What's the purpose for filtering on rubocop messages? Currently there is additional a check for duplicates and a Rails security scanner. For developers it shouldn't be important which specific engine complains, because every problem should be fixed ;) If there is a false positive it can be discussed with the others and for this specific case (or in generell) deactivated in codeclimate.
