### ISSUE TITLE
US_2.8: Log In for Application

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#65]
**As**
organizer

**I want to**
force people to login before the can apply for events

**In order to**
make sure that the application can be stored correctly in the system and assign applications to a registered user

**Dependencies:** #92

**Estimate:** 3

**Acceptance Criteria:**
- [ ] display an error message when user tries to apply for something and is not logged in
- [ ] text of error message: "Du musst angemeldet sein, um dich für Workshops bewerben zu können."
- [ ] button error error takes user to login page
- [ ] after login user is taken directly to application page
- [ ] another button takes user back to the event overview
- [ ] works for all apply-buttons
- [ ] error page looks like this: ![selection_021](https://cloud.githubusercontent.com/assets/16731894/21134231/1d2964de-c11d-11e6-9d98-55c04e4faa39.png)

**Comment by Square0ne** [comment]
no redirection
