### ISSUE TITLE
Refactor Workshop Request Page

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swt2/workshop-portal#656]
- [x] split "Persönliche Daten" to "Schulinformationen"  and "Lehrerinformationen" and distribute the information accordingly
- [x]  Don't ask for the Adress of the Teachers but instead the address of the school. This should also be changed in the database.
- [x]  The telephone number should be the cell phone number of the teacher. Please state this in the text.

- [x] Ask additionally for the class/year of the pupils int the workshop information section. 
- [x] In the label next tot the field asking for the "Kenntnisstand" please state that this should be descriptive (more than Anfänger, Fortgeschritten, Experte) as this helps to adapt the workshop best to the needs of their pupils. 
- [x] Make this also a field that looks as if you should put at least 3 lines in.

**Comment by ekrebs5** [comment]
the grade attribute was added in model and view, but does not seem to be saved correctly

**Comment by ekrebs5** [comment]
also: tests
