### ISSUE TITLE
Add additional information to workshop request page

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swt2/workshop-portal#657]
- [x] ask how many pupils are in computer science related courses / AGs of the pupils wanting to visiting

- [x] provide checkbox asking wether they wish for tour over the campus

- [x] provide checkbox asking wether they wish for informations about the study options at HPIs

- [x] make sure admins and organizers have access to results of this data

**Comment by ekrebs5** [comment]
@annkatrinkuessner does the 4th point mean that only admins and organizers should see it, or that coaches can see it too but the other two should have special tests etc

**Comment by annkatrinkuessner** [comment]
everybody involved in organizing the camps should have access to the send data. therefore, coaches, as well as admins and organizers, should have access.

**Comment by corinnaj** [comment]
As far as I can tell this is already the case. All three roles have access to the "show page" of requests.
