### ISSUE TITLE
Hide edit button on other ones profile page

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#666]
**As**
organizer 

**I want to**
not see the edit ("Bearbeiten") button on the profile page of other users

**in order to**
avoid the unauthorized error (Du bist nicht authorisiert diese Aktion auszuführen.)

# Acceptance criteria

- Organizers do not see the edit button of other users.

- All users (including organizers) can still edit their own profile

**Comment by cmfcmf** [comment]
Closing as wontfix, because profiles go away.
