### ISSUE TITLE
Link source code and website

### ISSUE THREAD

**Issue by niccokunzmann** [hpi-swt2/workshop-portal#670]
In order to improve the platform, I would like to know where the source code is hosted and where I can see the currently deplozed version of the source code.

- [x] Put a link to github into the footer https://github.com/hpi-schuelerklub/workshop-portal/
- [x] add the link http://workshopportal.herokuapp.com/ to the description in the README file
- [x] set the top link next to the description of the repository to http://workshopportal.herokuapp.com/

**Comment by niccokunzmann** [comment]
The footer code is gone in the master branch.

1. here: https://github.com/hpi-schuelerklub/workshop-portal/blob/af76e08a8b77aa91d15b22a2c195778024451a56/app/views/layouts/application.html.erb#L65
2. gone: https://github.com/hpi-schuelerklub/workshop-portal/blob/master/app/views/layouts/application.html.erb#L41

I wonder where the footer is.

**Comment by bjrne** [comment]
Our standard branch is `dev` at the moment, this might resolve your wonders? 🙂
