### ISSUE TITLE
Look at errbit

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swt2/workshop-portal#692]
Is the Errbit link up to date? Does someone has the login credentials and is it in use? And should we link it there?
see #690

**Comment by cmfcmf** [comment]
IMHO we should remove Errbit references for now. I don't think anyone ever really used it anyways 😄

**Comment by bjrne** [comment]
I think the earliest it makes sense to use it again would be in the final deployment, or at least any other kind of monitoring
