### ISSUE TITLE
US_2.9: Well Formatted Errors In Forms

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#85]
**As**
pupil

**I want to**
see well formatted error message when entering information incorrectly into fields

**In order to**
 have a better user experience (save my eyes from bleeding)

**Dependency:**  

**Estimate:** 13

**Acceptance criteria**
- [x] error should look like this ![selection_014](https://cloud.githubusercontent.com/assets/16731894/20704205/ac57d208-b61e-11e6-9393-a6fed6317ab5.png) (in addition to error at the top)
- [x] error at the top of the form should be German ("In x Feldern sind Fehler aufgetreten")
- [ ] works for all sites where forms require vaildated input fields
- [x] make input field great again :wink: 
- [x] remove detailed error messages on top 
- [x] show only header translated to German
- [x] error message next to field

**Comment by Square0ne** [comment]
Remove detailed error messages on top / translate header to German / Error message beside field
