### ISSUE TITLE
US_2.10: Role Management Page

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#87]
**As**
organizer/admin

**I want to**
adjust the roles of other users 

**In order to**
deny or grant them special access rights

**Dependencies:** None

**Estimate:** 13

**Acceptance Criteria:**
- [x] reuse "Benutzerverwaltung" site 
- [x] remove id and display user name
- [x] user name is link to detail page of the user
- [x] role is selectable in a dropdown next to every user
- [x] current role is the selected choice in the dropdown
- [x] roles can be saved via save button
- [x] users can be filtered by name via search bar 
- [x] max 100 users per page
- [x] can navigate through pages if more than 100 users
- [x] accessible via entry in dropdown (top right; only for admins and organizers)
- [x] access via url without according rights lead to error (not authorized...)
- [x] translate everything
- [x] the roles should be named: "Nutzer, Coach, Organisator, Admin"
- [x] Sortierung nach Name
- [x] Bootstrap Seitennavigation
- [x] Localisation der Zeit
- [x] Fehlermeldung anzeigen, wenn über URL geöffnet, aber ohne richtige Rechte
- [x] organizers can't change the role of anyone to admin (only admins can to this)
- [x] Organiser-Rechte und -Funktionen implemtieren

**Comment by Square0ne** [comment]
organizer can change organizer and lower 
admins can change admins and lower
use paging (ex 100 per page)
add button to drop down (only visible for organizer/admin)

**Comment by hendraet** [comment]
You should reuse the "Nutzer"-overview. Just display the right name, the dropdown, and remove the "Bearbeiten" button

**Comment by JuliusCosmoRomeo** [comment]
![image](https://cloud.githubusercontent.com/assets/10089188/21360720/5ef3bc38-c6e1-11e6-8e5e-8c417b73d314.png)

which id field should be replaced? The "id"-field or the "user"-field which contains the user id?

**Comment by JuliusCosmoRomeo** [comment]
both ids should be removed and replaced with user name

**Comment by JuliusCosmoRomeo** [comment]
when user doesn't have name yet take e-mail
-> create method "name" that returns name if existing, e-mail otherwise

**Comment by JuliusCosmoRomeo** [comment]
translate roles (as for gender -> philipp)

**Comment by bjrne** [comment]
Pay attention to #222 and #115. The id column will disappear shortly.

**Comment by hendraet** [comment]
Bootstrap Seitennavigation
Localisation der Zeit

**Comment by hendraet** [comment]
Sortierung nach Name
Organiser implemtieren
Fehlermeldung anzeigen, wenn über URL
