### ISSUE TITLE
US_2.11: Fill In Profile Before Application

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#88]
#**As**
organizer

**I want**
pupils to fill in their profile before applying to anything

**In order to**
make sure that all necessary data is provided

**Dependencies:** #92

**Estimate:** 5

**Acceptance Criteria:**
- [ ] display an error message when user tries to apply for something and mandatory profile fileds are not filled
- [ ] text of error message: "Du musst erst dein Profil ausfüllen, um dich für Workshops bewerben zu können. [Zum Profil](https://en.wikipedia.org/wiki/Profil)"
- [ ] link in error takes user to profile
- [ ] display error on same page
- [ ] works for all apply-button

**Comment by Square0ne** [comment]
when clicking on apply button
